### ISSUE TITLE
feature request: Spaces support

### ISSUE THREAD

**Issue by williamkray** [mautrix/signal#102]
I currently use the Spaces beta, and it would be excellent to have support for Spaces added to this bridge to allow all signal-related messages lumped together similar to the existing Communities support.

**Comment by MayeulC** [comment]
To detail more, I would like to:
* Add every "DM" and group chat to the space
* Add every contact to the space
  * even those the user hasn't spoken with, maybe as "suggested rooms". It could be a subspace, but I am not sure how supported  those are for now.
* Add the management DM with the signal bot to that space.

**Comment by ShadowJonathan** [comment]
WhatsApp Mautrix has this now, so it should be relatively easy to replicate the feature

**Comment by Tropaion** [comment]
> WhatsApp Mautrix has this now, so it should be relatively easy to replicate the feature
> 
> Edit: Wrong language, whoops

Wanted to recommend to replicate it from Discord Mautrix, but is also Go.
But I would really like the Space support, I'm using it with WhatsApp and Discord and is really nice.

**Comment by Glotzon** [comment]
Yes, please, this feature is urgently missing. Maybe even the signal bridge should by default automatically generate a space and place everything underneath.

**Comment by Tropaion** [comment]
I have just seen, heisenbridge is also written in python and already supports spaces: https://github.com/hifi/heisenbridge/blob/master/heisenbridge/space_room.py

Maybe this would make it easier to implement it. Sadly I don't know much about python.

**Comment by Jaffex** [comment]
I adopted the [changes](https://github.com/mautrix/whatsapp/pull/413) made to the whatsapp bridge and added it to the signal bridge over at https://github.com/Jaffex/signal/tree/add/spaceGeneration

Currently however, a room would need to be recreated for it to be added on an already existing installation.

@tulir would you be interested in a pull request and would you have any advice on how to add already existing rooms to the space?

**Comment by sumnerevans** [comment]
@Jaffex you can check out what I did in LinkedIn:

* https://github.com/beeper/linkedin/commit/e62020dcf219f3371f608ceb9d8e5d4acd47f505
* https://github.com/beeper/linkedin/commit/3d4afcd24b9fb9f87cd722e50a3a6d873dccc10d

Also, I think the preferred nomenclature is `personal_filtering_spaces` since that's what WhatsApp does: https://github.com/mautrix/whatsapp/blob/master/example-config.yaml#L105-L107
