### ISSUE TITLE
GIFs are not converted to mp4 files.

### ISSUE THREAD

**Issue by undercoverturbo** [mautrix/signal#109]
When transmitting GIFs from Signal to Matrix, they should be converted to mp4 files, in order to allow other bridges like whatsapp to properly transmit them, as well.
Currently GIFs are not transmitted as mp4 files, but as GIFs.

**Comment by tulir** [comment]
I don't see any reason to convert them, GIFs work fine with the WhatsApp bridge and on all Matrix clients.

**Comment by undercoverturbo** [comment]
Hi, the reason is, that when bridging GIFs from Telegramm to WhatsApp, this works, since the GIFs are converted. Pretty much any direction between WhatsApp, Matrix, Telegramm and Signal work.
Except for GIFs sent in Signal. Those are bridged to Matrix, but then not sent to WhatsApp at all, and break in Telegramm.
I just tested this again.

**Comment by tulir** [comment]
None of the bridges convert anything. Both Telegram and WhatsApp seem to be fine with gifs bridged from Signal

**Comment by undercoverturbo** [comment]
Hm, when sending a gif in WhatsApp, it is bridged as video.mp4. Telegram bridges it as mp4.mp4. Signal sends ist as a .gif file.
I already read in another issue (I think it was at the WhatsApp bridge) that the bridges are supposed to recieve MP4 files from Matrix, not .gif Files. Which is why Signal -> WhatsApp is not working. So either the problem is, that the WhastApp bridge does not support .gif Files, or that Signal does not convert/send the .gif file to a .MP4 file, like the other bridges do.
