### ISSUE TITLE
Connection to signald.sock failed

### ISSUE THREAD

**Issue by horphi0815** [mautrix/signal#121]
Hi,

i run signal on unraid/docker and have the error:

[2021-09-09 13:27:57,309] [[31;1mERROR[0m@[35;1mmausignald[0m] Connection to /var/run/signald/signald.sock failed: [Errno 2] No such file or directory

do i need to assign this directory?

best regards,
Phil

**Comment by czebiniak** [comment]
what was the solution? I also have this issue on unraid

**Comment by czebiniak** [comment]
nvmd, I figured it out, to any future unraiders the solution was to download a separate signald docker, and map the /signald to both the mautrix-signal and signald docker
