### ISSUE TITLE
Verify bot certificates?

### ISSUE THREAD

**Issue by Just-Insane** [mautrix/signal#122]
I haven’t seen it mentioned in any docs or issues opened here, but it doesn’t seem to be possible to verify the bots certificates.

It also seems that when doing double-puppeting, certificates/devices are added to your account that cannot be verified.

I’m new to Matrix and not sure if this is a security issue, but some UIs mark the encrypted room as untrusted/less secure due to these issues?

**Comment by tulir** [comment]
You can do trust-on-first-use by just manually marking the device on the bridge bot as verified, other than that it can't currently be verified. (in element web: click on "1 session" -> click on session name -> manually verify by text)

> It also seems that when doing double-puppeting, certificates/devices are added to your account that cannot be verified.

No, double puppeting does not add any e2ee devices.

**Comment by Jaffex** [comment]
I'm having this problem as well - already had the signal bridge running and only today enabled encryption.

Would it break anything if I'd remove the existing Signal Bridge-Session from within my client and then restart the bridge?

I'd expect the "new unverified session" to pop up then, where I can manually verify, as stated by @tulir

**Comment by Dual-0** [comment]
I have verified the device via text but still gets unencrypted messages from the bot in the encrypted "management room"

![image](https://user-images.githubusercontent.com/37346547/150824573-a1ab8bc0-0579-4538-b23f-ebe24fc13398.png)

**Comment by sumnerevans** [comment]
Encrypting messages to the management room is not implemented. It reads them encrypted, but doesn't send encrypted messages back.
