### ISSUE TITLE
Prevent multiple users from logging into the same Signal account

### ISSUE THREAD

**Issue by Half-Shot** [mautrix/signal#123]
I connected my Signal account to two Matrix accounts, but the bridge didn't invite my second user to an DMs. I'd either expect the bridge to disallow two connections to an account OR ensure all users are invited to PM rooms.

I could work around this by using the `pm` command.

**Comment by tulir** [comment]
It's supposed to be disallowed, but looks like I forgot both the unique constraint in the `user` table and the code to handle duplicate logins :D
