### ISSUE TITLE
Exception in Matrix event handler - Can't send Picture

### ISSUE THREAD

**Issue by multi-max** [mautrix/signal#128]
Hi,

I get an error when I try to send a picture to my signal contact. I can receive images, but not send them

```
mautrix-signal      | [2021-09-20 16:15:36,916] [ERROR@mau.as] Exception in Matrix event handler
mautrix-signal      | Traceback (most recent call last):
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix/appservice/as_handler.py", line 194, in try_handle
mautrix-signal      |     await handler_func(event)
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 476, in int_handle_event
mautrix-signal      |     await self.handle_encrypted(evt)
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 382, in handle_encrypted
mautrix-signal      |     await self.int_handle_event(decrypted)
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 474, in int_handle_event
mautrix-signal      |     await self.handle_message(evt.room_id, evt.sender, evt.content, evt.event_id)
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 297, in handle_message
mautrix-signal      |     await portal.handle_matrix_message(sender, message, event_id)
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 289, in handle_matrix_message
mautrix-signal      |     await self.signal.send(username=sender.username, recipient=self.chat_id, body=text,
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/signald.py", line 139, in send
mautrix-signal      |     await self.request_v1("send", username=username, messageBody=body,
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 221, in request_v1
mautrix-signal      |     return await self.request(command, expected_response=command, version="v1", **data)
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 215, in request
mautrix-signal      |     resp_type, resp_data = await self._raw_request(command, **data)
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 212, in _raw_request
mautrix-signal      |     return await asyncio.shield(future)
mautrix-signal      | mausignald.errors.ResponseError: AttachmentInvalidException: /tmp/mautrix-signal-XXXX: /tmp/mautrix-signal-XXXX (No such file or directory)
```
When I look in the tmp directory, the file is there:
```
root@multimax:/opt/container/matrix-synapse# docker exec -it mautrix-signal /bin/bash
bash-5.1# ls -la /tmp/
total 36
drwxrwxrwt    1 root     root          4096 Sep 20 16:15 .
drwxr-xr-x    1 root     root          4096 Sep 20 15:55 ..
-rw-r--r--    1 root     root         26889 Sep 20 16:15 mautrix-signal-XXXX
```

Can someone help me?
Any Ideas?

**Comment by wvffle** [comment]
This happens to me also.

**Comment by multi-max** [comment]
Are there any updates yet?

**Comment by multi-max** [comment]
Hi @tulir 
I got an uptdate, that you tryed to fix the issue.
I updated the container from the image (dock.mau.dev/mautrix/signal:latest sha256:ba11c65be99172882bf669850acda77cd45c9ffd07867e69169f71aa250a9627) and tryed to send a Picture to my signal friend. 

And the error occurred:
![image](https://user-images.githubusercontent.com/67010223/158058242-ef586710-9bed-4d28-b38d-450eaf14c2e9.png)

Docker Log:
mautrix-signal      | [2022-03-13 11:58:21,031] [DEBUG@mau.portal.3b9299f4-c551-4a7d-aa08-e966c8b5c758] Sending Matrix message $KK8zJRSjJISjP7jQTZrBW5hS2LZF7zPAnrBGwZrs5uc to Signal with timestamp 1647172701014
mautrix-signal      | [2022-03-13 11:58:21,031] [INFO@mau.portal.3b9299f4-c551-4a7d-aa08-e966c8b5c758] Send attempt 0. Attempting to send $KK8zJRSjJISjP7jQTZrBW5hS2LZF7zPAnrBGwZrs5uc with a805129c-5bf2-47ea-9cd6-286d30acfe82
mautrix-signal      | [2022-03-13 11:58:21,032] [DEBUG@mausignald] Request a805129c-5bf2-47ea-9cd6-286d30acfe82: send
signald             | 11:58:21.075 [a805129c-5bf2-47ea-9cd6-286d30acfe82-send] ERROR io.finn.signald.clientprotocol.v1.exceptions.InternalError - error uploading attachment
signald             | java.io.FileNotFoundException: /tmp/mautrix-signal-579d2085-e805-4019-9cdb-9c34f9c3eaf6 (No such file or directory)
signald             |   at java.io.FileInputStream.open0(Native Method) ~[?:?]
signald             |   at java.io.FileInputStream.open(Unknown Source) ~[?:?]
signald             |   at java.io.FileInputStream.<init>(Unknown Source) ~[?:?]
signald             |   at io.finn.signald.clientprotocol.v1.JsonAttachment.asStream(JsonAttachment.java:106) ~[signald.jar:?]
signald             |   at io.finn.signald.clientprotocol.v1.SendRequest.run(SendRequest.java:99) [signald.jar:?]
signald             |   at io.finn.signald.clientprotocol.v1.SendRequest.run(SendRequest.java:46) [signald.jar:?]
signald             |   at io.finn.signald.clientprotocol.Request.<init>(Request.java:146) [signald.jar:?]
signald             |   at io.finn.signald.clientprotocol.ClientConnection$RequestRunner.run(ClientConnection.java:160) [signald.jar:?]
signald             |   at java.lang.Thread.run(Unknown Source) [?:?]
mautrix-signal      | [2022-03-13 11:58:21,154] [ERROR@mau.portal.3b9299f4-c551-4a7d-aa08-e966c8b5c758] Sending message failed
mautrix-signal      | Traceback (most recent call last):
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 407, in _handle_matrix_message
mautrix-signal      |     retry_count = await self._signal_send_with_retries(
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 476, in _signal_send_with_retries
mautrix-signal      |     await send_fn(sender, event_id, req_id=req_id, **send_args)
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/signald.py", line 251, in send
mautrix-signal      |     resp = await self.send_raw(
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/signald.py", line 225, in send_raw
mautrix-signal      |     resp = await self.request_v1(
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 244, in request_v1
mautrix-signal      |     return await self._request(command, expected_response=command, version="v1", **data)
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 238, in _request
mautrix-signal      |     resp_type, resp_data = await self._raw_request(command, **data)
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 235, in _raw_request
mautrix-signal      |     return await asyncio.shield(future)
mautrix-signal      | mausignald.errors.InternalError: java.io.FileNotFoundException: java.io.FileNotFoundException: /tmp/mautrix-signal-579d2085-e805-4019-9cdb-9c34f9c3eaf6 (No such file or directory)
mautrix-signal      | [2022-03-13 11:58:21,156] [ERROR@mau.portal.3b9299f4-c551-4a7d-aa08-e966c8b5c758] Failed to handle Matrix message $KK8zJRSjJISjP7jQTZrBW5hS2LZF7zPAnrBGwZrs5uc
mautrix-signal      | Traceback (most recent call last):
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 308, in handle_matrix_message
mautrix-signal      |     await self._handle_matrix_message(sender, message, event_id)
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 407, in _handle_matrix_message
mautrix-signal      |     retry_count = await self._signal_send_with_retries(
mautrix-signal      |   File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 476, in _signal_send_with_retries
mautrix-signal      |     await send_fn(sender, event_id, req_id=req_id, **send_args)
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/signald.py", line 251, in send
mautrix-signal      |     resp = await self.send_raw(
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/signald.py", line 225, in send_raw
mautrix-signal      |     resp = await self.request_v1(
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 244, in request_v1
mautrix-signal      |     return await self._request(command, expected_response=command, version="v1", **data)
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 238, in _request
mautrix-signal      |     resp_type, resp_data = await self._raw_request(command, **data)
mautrix-signal      |   File "/opt/mautrix-signal/mausignald/rpc.py", line 235, in _raw_request
mautrix-signal      |     return await asyncio.shield(future)
mautrix-signal      | mausignald.errors.InternalError: java.io.FileNotFoundException: java.io.FileNotFoundException: /tmp/mautrix-signal-579d2085-e805-4019-9cdb-9c34f9c3eaf6 (No such file or directory)

Could you help me?

Thanks Max

**Comment by tulir** [comment]
This has always been an incorrect config on your side (`outgoing_attachment_dir` must be a directory that signald can access), not a bridge issue.

**Comment by multi-max** [comment]
@tulir good Point, that was my fault. Thanks for your help.
