### ISSUE TITLE
Editing message from Matrix resends message without explanation to Signal chat

### ISSUE THREAD

**Issue by jakecoppinger** [mautrix/signal#134]
When editing a message on the Matrix side, the bridge re-sends a message into the Signal chat.

If this message was prefixed with something like "{user} edited their message to:" it would be less confusing for Signal users.

**Comment by paulRbr** [comment]
Ideally, the mautrix/signal bot would delete the previous Signal message instead of adding test to the newly edited message.

Currently the bot can already delete a Signal message when the message is deleted from the Matrix room, so it should be able to delete the previous message on edition too :slightly_smiling_face:

**Comment by bew** [comment]
Hmmm yeah maybe ok, you're right..

**Comment by a22sc** [comment]
In my signal the edited message is just appended and the original one stays. Might be better to delete the original message

**Comment by olmari** [comment]
And/or prefix with * or something? I mean there's plenty ways to skin the cat where "upstream" doesn't support edits...

**Comment by sibbl** [comment]
I'd like to bring this topic up again as Signal received native message editing support a few weeks ago: https://community.signalusers.org/t/edit-sent-messages/975/650

This would basically make this bug a new feature request.

**Comment by olmari** [comment]
@sibbl as now "this" current mautrix-signal (and also related signald) is basically EOL:ed and new one written in go is coming fast, this issue might be obsolete in itself, at least for legacy version it is no-go.
