### ISSUE TITLE
audio Messages displayed as downloadable file 

### ISSUE THREAD

**Issue by Happyfeet01** [mautrix/signal#144]
Hello, 

When i send an Voice Message from Element Android/Web or Fluffchat Android to an Signal contacts or rooms, the Message are displayed as an downloadable m4a file. Messages from Signal are oga files. Maybe that's the reason.    

I remember that this worked in the past. 

Synapse 1.45.0
Signal Bridge     0.2.0+dev.[2fb9380b]
Debian 11 Server

Installed via ansible deploy

**Comment by Happyfeet01** [comment]
Any Update? 

Messages from Signal to Matrix are aac files. 
Messages from element web/Android are m4a files.  Signal can't open  m4a Files as Voicemessage.

**Comment by mathix420** [comment]
Same here as well
