### ISSUE TITLE
Some usernames are not synced from signald

### ISSUE THREAD

**Issue by NCLI** [mautrix/signal#145]
What happens:

1. A message arrives from another user, either as a private message, or through a group.
2. The user is often only identified by their phone number, or as "unknown user".

What should happen:
1. A message arrives from another user, either as a private message, or through a group.
2. The user is identified by their username.

When I look users or groups up directly using signald, the names are there. Something seems to be broken in between signald and the bridge, The command "!signal sync" does nothing, other than reply "Sync complete".

**Comment by NCLI** [comment]
I'm on mautrix-signal 0.2.0 according to the log. I just ran `pip install --upgrade mautrix-signal[all]`, but nothing seems to have changed.

**Comment by sumnerevans** [comment]
The changes are not in a release yet. I think you can do a `pip install` and point it at this repo.
