### ISSUE TITLE
Migrate from the subscribe v0 API to the v1 API

### ISSUE THREAD

**Issue by jaller94** [mautrix/signal#151]
## Description
signald received a request with no version. This will stop working in a future version of signald. Please update your client. Client authors, see https://signald.org/articles/protocol-versioning/

## Software
Signald version: signald/signald:0-15-0
Signal bridge version: signal-bridge-0.2.0

## Logs
```
INFO  io.finn.signald.clientprotocol.ClientConnection - signald received a request (request ID: [[UUID redacted]]) with no version. This will stop working in a future version of signald. Please update your client. Client authors, see https://signald.org/articles/protocol-versioning/
WARN  io.finn.signald.clientprotocol.ClientConnection - client org.newsclub.net.unix.AFUNIXSocketCredentials@1c2f02[pid=0;uid=0;gids=[0]] sent a v0 subscribe request. v0 support will be removed at the end of 2021. Please update your signald client. Client authors, see https://signald.org/articles/protocol-versioning/#deprecation
```

**Comment by ChewingBever** [comment]
I've just noticed this in my logs as well. Is this something that's being worked on, or will we have to use a slightly outdated signald version after 2021?

**Comment by sumnerevans** [comment]
signald won't deprecate it until mautrix-signal is off of the old subscribe version.
