### ISSUE TITLE
Force re-creation of all portals?

### ISSUE THREAD

**Issue by IngwiePhoenix** [mautrix/signal#157]
I just installed the bridge and it was quite easy to do.

However, except for one room, I don't get any bridged portals whatsoever, although my list of chats is quite full on my phone. Any idea how I can sync that over?

Thanks!

**Comment by MayeulC** [comment]
You are probably looking for this?

https://github.com/mautrix/signal/blob/2ee27d6056aa845eb30fb4267699498a37275694/mautrix_signal/example-config.yaml#L132-L133

Otherwise, a portal room will be created as soon as there is some activity.
