### ISSUE TITLE
[Enhancement] Search for a specific user

### ISSUE THREAD

**Issue by derritter88** [mautrix/signal#158]
Hello @tulir ,

it would be a nice to have feature if a Matrix user could search with a phone number for another user.
According to signald it should be possible -> https://signald.org/protocol/actions/v1/get_profile/

With this feature it should be possible to check if a person uses Signal or not.

**Comment by tulir** [comment]
Doesn't seem possible, but you can already just try to send a message

**Comment by derritter88** [comment]
Not sure why this should not be possible?
"Get_Profile: Get all information available about a user"

**Comment by derritter88** [comment]
Digging a bit deeper I found a sample here -> https://gitlab.com/signald/signald/-/issues/236 (last screenshot) and played a bit around:

`raw --user v1.get_profile {"address":{"uuid":"<uuid of a user>"},"async":"false"}`

or

`raw --user v1.get_profile {"address":{"number":"<phonenumber of a user>"},"async":"false"}` 

return a JSON with data.

**Comment by derritter88** [comment]
or an error message if a user does not exist:
`Error sending request: InternalError: org.whispersystems.signalservice.api.push.exceptions.UnregisteredUserException`

Initial I create a regular converstation and mautrix-signal does not mentioned anything that the other user does not use Signal.

**Comment by tulir** [comment]
It probably requires adding a new request type to signald that checks if a phone number is on Signal. `get_profile` doesn't do that.

**Comment by derritter88** [comment]
Why?
Either you get information of a uuid or phone number or you get an error?
Would't that be the sufficient?

**Comment by tulir** [comment]
You don't get an uuid (unless you already have the user in contacts or something) nor an error

**Comment by derritter88** [comment]
Yeah but it also works with the phone number.

**Comment by thefinn93** [comment]
@derritter88 hello, I'm the author of signald. @tulir is correct that `get_profile` does not search for users on Signal. it only returns known profiles or contacts synced from your main device. There is currently no mechanism in signald to check if a particular phone number is registered on Signal.

**Comment by derritter88** [comment]
Hello  @thefinn93 , this sound a little bit strange to me: I have stopped using Signal on my mobile phone around 5 years ago when I started self hosting messaging application.

After starting to play around with this bridge from @tulir I have registrated my phone number why the [shell](https://signald.org/articles/captcha/) .
Still I do not have any Signal application on my phone.

So that's my background.
But I am still able to run the command `raw --user v1.get_profile ....`  and view details from people I did not know when I was Signal in the past.

**Comment by thefinn93** [comment]
Well I'm not sure how you did that. I've just had a quick look at [the `get_profile` code](https://gitlab.com/signald/signald/-/blob/main/src/main/java/io/finn/signald/clientprotocol/v1/GetProfileRequest.java) and it definitely looks in the local data store (via `m.getAccountData()`) and only makes a network request if it finds a profile that hasn't been refreshed recently.

**Comment by derritter88** [comment]
I usually run this cmd `raw --user v1.get_profile {"address":{"number":"<phonenumber of a user>"},"async":"false"}`.

**Comment by derritter88** [comment]
@thefinn93 do you use Matrix or have PGP?
So I can send you some real data example.

**Comment by thefinn93** [comment]
I'm on matrix at `@finn@beeper.com`
