### ISSUE TITLE
Cannot register - Authorization failed!

### ISSUE THREAD

**Issue by alkesander** [mautrix/signal#160]
Hi, 
I have been trying to register for some time so far and am failing when sending the sms code every time. Let me sum up the issue:
1. I have joined bridge bot room
2. I have executed: `register --captcha <captcha> <number>`
3. Bridge bot replied: `Register SMS requested, please enter the code here.`
4. I have received a SMS: `<#>Twój kod weryfikacyjny SIGNAL to: <code> doDiFGKPO1r` - which basically means something like 'Your identification code is ....' and then this weird string. 
5. When I put my verification code (just the number) I'm getting: `Unhandled error while handling command:` and the error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 406, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix_signal/commands/auth.py", line 126, in enter_register_code
    account = await evt.bridge.signal.verify(username, code=evt.args[0])
  File "/opt/mautrix-signal/mausignald/signald.py", line 124, in verify
    resp = await self.request_v1("verify", account=username, code=code)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 223, in request_v1
    return await self.request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 217, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 214, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.AuthorizationFailedException: [403] Authorization failed!
```
I am really confused what I can be doing wrong. Also this weird string after the number is every time the same. I have just tried to delete my account and register with a blank state to signal using this bridge and nothing changed. Now I have no more idea how I can get this working.... Please let me know if you have any idea how I can pas through that error. Would appreciate a lot! 

I'm trying to convince more people to use matrix but to do that signal (most used communicator in my daily live) is necessary. Instead it's hard to convince people to add just another communicator.

**Comment by alkesander** [comment]
Hi,
I had deleted it without any results....

**Comment by karpaz** [comment]
I have this problem too

**Comment by GeneralZero** [comment]
Same here

**Comment by Karamelmar** [comment]
+1

**Comment by GeneralZero** [comment]
Seems to be fixed for me now.

**Comment by Redskyer** [comment]
I have the same problem now. How did you handle it?

**Comment by Redskyer** [comment]
I did it. The trick is just to put in:
<code> doDiFGKPO1r
NOT the whole message.
