### ISSUE TITLE
 Signal Bridge doesn't bridge SMS on Android

### ISSUE THREAD

**Issue by rtanglao** [mautrix/signal#175]
Not sure if it is even possible to bridge Android SMSes over to Matrix! (and it's a feature that only exists on Signal for Android; doesn't work on Signal for iOS)

**Comment by HNGamingUK** [comment]
Signal does not handle SMS via their systems and as such the Signal bridge won't work with it. It is just an SMS client on Android. 

You could however use the following bridge https://github.com/benkuly/matrix-sms-bridge for SMS.

**Comment by tulir** [comment]
[mautrix-imessage](https://github.com/mautrix/imessage) can also bridge SMS from Android: https://docs.mau.fi/bridges/go/imessage/android/setup.html
