### ISSUE TITLE
media not beeing bridged - InvalidAttachmentError: /tmp/[...]  (No such file or directory)

### ISSUE THREAD

**Issue by adb-sh** [mautrix/signal#176]
Hey :)
I'm unable to send media content like images via the bridge. Receiving works though. (I'm using the default docker-compose setup.)
The bridged user responses with this error notice in the room:
```
Your message was not bridged: InvalidAttachmentError: /tmp/mautrix-signal-{{ uuid }} (No such file or directory)
```
But the file does actually exist in the mautrix container.

corresponding docker-compose logs:
```
signald_1  | Nov 25, 2021 8:37:50 AM okhttp3.internal.platform.Platform log
signald_1  | WARNING: A connection to https://cdn.signal.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE)
```

**Comment by tulir** [comment]
That sounds like the file doesn't exist in the signald container

**Comment by adb-sh** [comment]
ahh, that would make sense. so should i create a volume for the `/tmp` directory and pass it to both containers then?

**Comment by tulir** [comment]
The easiest solution is to put it in `/signald/attachments` because `/signald` is shared anyway (and that's where the incoming attachments are). It's mentioned in step 4 of the docker install docs https://docs.mau.fi/bridges/python/signal/setup-docker.html

**Comment by adb-sh** [comment]
ouh, i must have missed that during setup. thanks for the help, it works now ^^
