### ISSUE TITLE
New people writing in group chats automatically pop up as DM

### ISSUE THREAD

**Issue by stoically** [mautrix/signal#177]
I'm in a few rather large group chats and if new people join the group and type something, a new DM with no content gets created with them - while the signal app never shows anything related to those persons. Is this expected behavior? And if so, is there any way to prevent this?

Previously it was always an invite to a DM, until I activated double puppeting, now the DM gets directly created.

Also tried my luck with the following two configurations, but they didn't help either:

```
    # Whether or not to create portals for all groups on login/connect.
    autocreate_group_portal: false
    # Whether or not to create portals for all contacts on login/connect.
    autocreate_contact_portal: false
```

If I can provide more information, please let me know. Thanks for working on bridges!

**Comment by stoically** [comment]
Attached my full configuration (things enclosed in `{{ }}` are ansible templating things). Encryption is not enabled.

[mautrix-signal.zip](https://github.com/mautrix/signal/files/7653524/mautrix-signal.zip)

**Comment by sumnerevans** [comment]
No, definitely not expected behaviour. I'll look into (we have seen this happen with Beeper bridges lately as well).

**Comment by stoically** [comment]
Not sure why, but for me it seems to be solved. Haven't had any unexpected DM for a while.

**Comment by tulir** [comment]
Oh yeah, this was probably fixed a few weeks back
