### ISSUE TITLE
Discover and reuse existing DM rooms instead of creating new ones

### ISSUE THREAD

**Issue by MayeulC** [mautrix/signal#183]
Some time ago, I had a few issues with the bridge, which led me to uninstall it.

Reinstalling it went fine, but it's re-creating every room. I think the bridge should be able to tell when a direct chat between a signal user and a matrix user already exists, and use that one.

The same issue also exists for group chats: a new one is created, the old one is left un-updated even though the bot user still appears as a member. It might be more complex to handle, especially if there are also Matrix users inside.

One possible solution would be to use signal uuids (possibly hashed, maybe peppered with server name) to build Matrix room ids deterministically.

**Comment by tulir** [comment]
You can just use `clean-rooms` to clean up the old rooms

**Comment by witchent** [comment]
Maybe they don't want to loose the message history, so I agree that it would be nice if it would reuse old rooms (or if one could manually make a room belong to a certain signal chat maybe)

**Comment by MayeulC** [comment]
Yes, I would have liked to retain room history if possible, and space membership as well. To a lesser extent, Matrix users membership. It would have also been handy to contact users I was recently chatting with as these portals were already "open".

Another option to recognize rooms would be to put Signal metadata inside some custom event.

Thank you for mentioning `clean-rooms`, I had forgotten about it, and it wasn't clear to me that this is what it is for. I'll probably use it for now, but reusing the rooms would be nicer.
