### ISSUE TITLE
cannot reach the docker server? access forbidden

### ISSUE THREAD

**Issue by atuctuc** [mautrix/signal#186]
mach $ docker-compose pull
Pulling signald        ... done
Pulling mautrix-signal ... error
Pulling db             ... done

ERROR: for mautrix-signal  Head "https://dock.mau.dev/v2/tulir/mautrix-signal/manifests/latest": denied: access forbidden
ERROR: Head "https://dock.mau.dev/v2/tulir/mautrix-signal/manifests/latest": denied: access forbidden

**Comment by sumnerevans** [comment]
The path is now `dock.mau.dev/mautrix/signal`
