### ISSUE TITLE
 create a config file fails?

### ISSUE THREAD

**Issue by atuctuc** [mautrix/signal#187]
i try to install the mautrix docker from this manual:
https://docs.mau.fi/bridges/python/signal/setup-docker.html
i follow step 1. and 2.

step 3. to create a config file fails: 

root@anan:~/tmp/mautrix-signal# docker-compose up mautrix-signal
Pulling mautrix-signal (dock.mau.dev/mautrix/signal:)...
latest: Pulling from mautrix/signal
97518928ae5f: Pull complete
e83329694015: Pull complete
9e3843cf299c: Pull complete
d2ec3be1aa56: Pull complete
dd9ed6f5ef39: Pull complete
cbeab5edc729: Pull complete
84694c653631: Pull complete
Digest: sha256:64915276e70ddc804a08f19fe69f0d5e954c973f9afd663461785e6b52c1fe15
Status: Downloaded newer image for dock.mau.dev/mautrix/signal:latest
signald is up-to-date
Creating mautrix-signal ... done
Attaching to mautrix-signal
mautrix-signal    | [2021-12-14 15:47:47,818] [CRITICAL@mau.init] Configuration error: homeserver.address not configured

**Comment by tulir** [comment]
That only happens when the config exists

**Comment by atuctuc** [comment]
no, there is no config.yaml in the folder

**Comment by atuctuc** [comment]
ah, i had to remove the subfolder "bridge"
