### ISSUE TITLE
Option to not bridge rooms when the user has never spoken to them on Signal before

### ISSUE THREAD

**Issue by Half-Shot** [mautrix/signal#190]
The bridge seems to sync all contacts, which includes people you know who have Signal but have not spoken to

**Comment by sumnerevans** [comment]
Are you possibly running into https://github.com/mautrix/signal/pull/180? We were accidentally creating portals for every user who sent a profile key update (not sure exactly when that happens, but it happens regularly enough that you can easily get a ton of portals to users that you've never communicated with.

**Comment by Half-Shot** [comment]
We should have pulled in that change since yesterday https://github.com/vector-im/mautrix-signal/commits/v0.2.1-mod-3, but it still seems to be occuring. Possibly new events causing it?

**Comment by tulir** [comment]
Is this still happening for you? I don't think we've had any new reports
