### ISSUE TITLE
Use Signal-default avatar when users have no avatar

### ISSUE THREAD

**Issue by ShadowJonathan** [mautrix/signal#197]
I currently have two users with whom i talk to on signal;

One user with the initials RS, and another with a custom text avatar "MJC";

![image](https://user-images.githubusercontent.com/22740616/149542089-72b66a17-6619-47e1-88a5-9b73416cf40b.png)
![image](https://user-images.githubusercontent.com/22740616/149542109-d1053ed9-5401-4386-91be-243cac384c9d.png)

Signal auto-generated the latter avatar, and I like it a lot.

Is it possible to request signal to generate these avatars for any user without a profile picture? If so, could the bridge start using them? (For uniformity)

**Comment by tulir** [comment]
That should probably be done by your client, not the bridge
