### ISSUE TITLE
can not add pm

### ISSUE THREAD

**Issue by xundeenergie** [mautrix/signal#209]
i can not add new im in matrix for new number.

if i try `pm +43xxxxxxxxxxx` (without spaces!!) i get the answer "Usage pm ...." from bridge bot.

The format is ok.
The number is already a contact in signal with chat-history.

One number was able after many retries, the other numbers not.

In logs for mautrix-signal i can see in debug that mattix sends something to mautrix and back without errors...

**Comment by xundeenergie** [comment]
i think the problem is:

i hab a working bridge for my private signal account.
then i added my work account on the second bridge.

on both i have many mirrored contacts, because i have joined my private addressbook on my workphone too...

now this contacts make big problems.

when i try to add a contact from the "private bridge" for pm on my "work bridge", i get in the work bridge the error-message

 `mautrix.errors.request.MExclusive: This user ID is reserved by an application service.
`

obviously the number is hashed on signal site and this hash ist the uuid, from which the matrix-id is generated from... and so it's impossible and causes problems with 2 bridges for one account.

**Comment by tulir** [comment]
Separate bridges need to have separate user ID namespaces (`username_template`), you can't run multiple bridges in the same namespace.
