### ISSUE TITLE
Multiple Signal reactions show as one on Matrix

### ISSUE THREAD

**Issue by LukeLR** [mautrix/signal#225]
Hi everyone,

I'm using mautrix-signal to bridge my Signal account from my phone into my Matrix account. This works great so far, thanks for this awesome piece of software.

However, I've noticed a bug: When multiple people react to a message with the same emoji on Signal, only the first reaction is shown in Matrix. This is how it looks on Signal:

![2022-02-17-131543_241x290_scrot](https://user-images.githubusercontent.com/3177243/154480056-473d5f72-090a-4421-a385-bf6c6fd0ca98.png)

This is how it looks on Matrix:

![2022-02-17-131548_217x224_scrot](https://user-images.githubusercontent.com/3177243/154480095-ff94223c-dd70-4e2f-9f45-17311157f0c2.png)

Notice that the last message has no reactions at all, and most reactions are missing on the other messages.

Let me know if I can provide any additional information for debugging this issue! Thanks in advance, and keep up the awesome work, this thing made my messaging life a lot better!

LukeLR

**Comment by tulir** [comment]
Sounds like an outdated bridge

**Comment by LukeLR** [comment]
I've updated the bridge to 0.2.2 and ran systemctl restart mautrix-signal, but the issue seems to persist. Any ideas?

**Comment by tulir** [comment]
Probably still too old

**Comment by LukeLR** [comment]
0.2.2 seems to be the latest release. Are you suggesting it is fixed only in the latest master?

**Comment by LukeLR** [comment]
I see, you've just released 0.2.3 :) I'll try that, thanks!

**Comment by LukeLR** [comment]
Hi, you were right, v0.2.3 fixed the issue. Thanks!
