### ISSUE TITLE
can not logout of session

### ISSUE THREAD

**Issue by schnuppikarotti** [mautrix/signal#231]
i tried this bridge and after i unlinked and deleted all signalrooms, the signal bridge is still in my sessions and i can not logout of this session. now its listed under unencrypted devices all the time and it seems still active getting messages

**Comment by tulir** [comment]
If you mean on the Matrix side, that's the session used for [double puppeting](https://docs.mau.fi/bridges/general/double-puppeting.html). It won't be logged out automatically, you have to remove it yourself.

**Comment by schnuppikarotti** [comment]
yeah i know. but its not working i tried several times to log it out, but its still there. thats the problem

**Comment by schnuppikarotti** [comment]
![screenshotsignal](https://user-images.githubusercontent.com/93953057/158027826-44bd2c01-4b24-468c-ab51-831304f5743c.png)

**Comment by schnuppikarotti** [comment]
i didnt used the bridge for several weeks. its not linked in my signal account, all rooms in matrix are deleted. i tried it several times to sign out. but its still there and its still active because "Last seen" ist refreshing

**Comment by tulir** [comment]
If the bridge is running and configured with automatic double puppeting, then it'll probably automatically relogin too

**Comment by schnuppikarotti** [comment]
so its not possible to logout the session as long the bridge is running?
