### ISSUE TITLE
Replies to replies have "null" attachment, causing broken display on desktop Signal app

### ISSUE THREAD

**Issue by Mikrz** [mautrix/signal#238]
I am using the most recent build of the bridge via github on commit https://github.com/mautrix/signal/commit/c4f7c975f84b25c79c61461f33b9d517347eeceb though this issue has been happening for a while.

When replying to another message that includes a reply, an invalid attachment is created and causes a null attachment icon to show on desktop Signal: 
![image](https://user-images.githubusercontent.com/767190/161654935-02014b41-bf81-40d7-98fd-720f70de3090.png)
Grey bubble was sent from Signal's Android app, blue was sent via the bridge. the "2345" message was sent with line 382 shown below removed, "back atcha" was sent with that line present.

I've confirmed this issue stems from this section: 
https://github.com/mautrix/signal/blob/7227540df8b33f2ad7bf4a8277fa2ece58a19676/mautrix_signal/portal.py#L375-L382

Apparently desktop Signal does not handle this odd behaviour as gracefully as Android and iOS. I would assume the fix would be to add the ability for the bridge to determine if the reply has an attachment or not per the TODO, though I'm unsure I'd be able to implement the fix in a quick manner so I'll leave this issue for now. 

Additionally, based on the commit (https://github.com/mautrix/signal/commit/498e0f2bab89daac07da8dc29a9f544bc2639f6a) that added that line to begin with, it was a quick fix for iOS to render replies properly so I would be unable to test any changes I make due to lack of an iPhone.

**Comment by maltee1** [comment]
I can't reproduce this with latest signal

**Comment by htayj** [comment]
@Mikrz what client are you using? I am having the same thing from ement, but not from element.

**Comment by Mikrz** [comment]
Sorry @htayj , this issue is from 2 years ago, and I've since stopped bridging Signal. The bug only appeared in the Signal app for me, and the only other app I used to connect to the matrix server was Element.
