### ISSUE TITLE
Status is not bridged

### ISSUE THREAD

**Issue by cutec-chris** [mautrix/signal#242]
or do i holding it wrong ?
On my server with mostly standard config i dont see contact status.
Is it possible to implement this ?

**Comment by tulir** [comment]
What status?

**Comment by cutec-chris** [comment]
Online-Status (the white/green sign in the lower right corner of an contact) 
but its also not bridget on the whatsapp bridge so iam wondering if thats an signal thing or not possible for bridges or not implemented or not impelmentable

**Comment by tulir** [comment]
Signal doesn't have online status

**Comment by cutec-chris** [comment]
should i open the same question/issue in mautrix-whatsapp ?
