### ISSUE TITLE
Database password sent to logs

### ISSUE THREAD

**Issue by anon8675309** [mautrix/signal#244]
# Objective
As an administrator, I want the logs to be free of sensitive information (keys, passwords, secrets, etc.) to prevent all users on the machine having access to secrets and minimize the damage in the event of a successful server compromise.

# Steps to reproduce
After starting mautrix-signal, run `systemctl status --no-pager -l mautrix-signal` to see the status.  This will result in output such as this:

```
Apr 14 13:38:04 comms python[34511]: [2022-04-14 13:38:04,662] [DEBUG@mau.init] Starting database...
Apr 14 13:38:04 comms python[34511]: [2022-04-14 13:38:04,663] [DEBUG@mau.db] Connecting to postgres://synapse:hunter1@localhost/synapse
Apr 14 13:38:04 comms python[34511]: [2022-04-14 13:38:04,730] [DEBUG@mau.init] Starting appservice...
```

The `systemctl` command can be run by any user on the machine.  It is not a privileged command.  This means any user on the server is able to get the database password.

In the event that logs are shipped off to a central logging server, it also means that the password will be available to anyone who has permission to look at those logs.

# Suggested change
Redact the password before writing this log message.  The output might look something like this:

```
Apr 14 13:38:04 comms python[34511]: [2022-04-14 13:38:04,662] [DEBUG@mau.init] Starting database...
Apr 14 13:38:04 comms python[34511]: [2022-04-14 13:38:04,663] [DEBUG@mau.db] Connecting to postgres://synapse:[REDACTED]@localhost/synapse
Apr 14 13:38:04 comms python[34511]: [2022-04-14 13:38:04,730] [DEBUG@mau.init] Starting appservice...
```

**Comment by tulir** [comment]
It's already redacted (as of last week)

**Comment by tulir** [comment]
https://github.com/mautrix/python/commit/0b79ec60e7fb4992a9557acb7f2548e2bf6aece1
