### ISSUE TITLE
Some characters in user's name don't show up in Element

### ISSUE THREAD

**Issue by andybalaam** [mautrix/signal#249]
I have a Signal contact whose name is Jörg. In Signal I see their name correctly.

In Element Web I see their name as J??rg:

![image](https://user-images.githubusercontent.com/76812/163994856-b04d2d6b-ccd0-45f7-a7fa-0b604bf3a366.png)

I am using an EMS-installed version of mautrix-signal so I presume it is reasonably up-to-date.

Please let me know if I can provide more helpful information.

**Comment by tulir** [comment]
That's a signald issue which happens when system locales are misconfigured. The signald docker image was recently overhauled to make locales less likely to be wrong, but it probably hasn't been deployed on EMS yet
