### ISSUE TITLE
Audio call notifications not displaying

### ISSUE THREAD

**Issue by seanfarley** [mautrix/signal#253]
I see that there is now a new feature for displaying a notification when someone calls you over Signal. That's great! Unfortunately, I get no such notification. I've updated to the latest version but wonder if there is a setting I need to configure? Or perhaps, my matrix bridge should be the primary device (currently my mobile device is registered as the main device)?

**Comment by sumnerevans** [comment]
Do other (non-call) messages work? Also note that it only works in DMs, not group chats (as that is a different type of call).

**Comment by seanfarley** [comment]
Other messages work, yeah. Even though it's a DM, I think matrix labels it as a group chat, so that might be it!

**Comment by seanfarley** [comment]
I opened a pm with a number but it said that I already had one opened so I'm not sure if that's the problem :-/
