### ISSUE TITLE
UnknownGroupError on an attempt to send a message

### ISSUE THREAD

**Issue by KitsuneRal** [mautrix/signal#267]
Here's an exception from the logs after what seems to be a Signal-side kick.
```
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]: [2022-05-25 10:23:49,187] [ERROR@mau.portal.ckhUbjiWfdqBVs3syZDdTAeWsqTJqNQ3wudfQHRdtxY=] Sending message failed
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]: Traceback (most recent call last):
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:   File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 409, in _handle_matrix_message
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:     retry_count = await self._signal_send_with_retries(
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:   File "/usr/lib/python3.9/site-packages/mautrix_signal/portal.py", line 478, in _signal_send_with_retries
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:     await send_fn(sender, event_id, req_id=req_id, **send_args)
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:   File "/opt/mautrix-signal/mausignald/signald.py", line 251, in send
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:     resp = await self.send_raw(
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:   File "/opt/mautrix-signal/mausignald/signald.py", line 225, in send_raw
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:     resp = await self.request_v1(
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 244, in request_v1
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:     return await self._request(command, expected_response=command, version="v1", **data)
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 238, in _request
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:     resp_type, resp_data = await self._raw_request(command, **data)
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:   File "/opt/mautrix-signal/mausignald/rpc.py", line 235, in _raw_request
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]:     return await asyncio.shield(future)
May 25 12:23:49 ---- matrix-mautrix-signal[3372645]: mausignald.errors.ResponseError: UnknownGroupError: unknown group requested
```

**Comment by maltee1** [comment]
I've seen this error when someone first logged into the bridge as a secondary device, then logged out and registered as a primary device. You can't send messages to groups that haven't accepted your new keys or something. Try to get someone in the group to send a message and see if that fixes your problem.

**Comment by zamadatix** [comment]
Expanding on the above I had to have someone trust my key, remove me from the group, and re-add me to the group in that order.

**Comment by maltee1** [comment]
remove and re-add? I suppose they could have also sent a message. Have you tried that?
Did you log into the bridge as a secondary device first and then as primary device though? I'm wondering whether this is always the case for an unknown group error. We might want to catch that and print a notice to the user with instructions on how to solve the problem.

**Comment by zamadatix** [comment]
The order of operations for me to get in this state was something like Android+linked Beeper -> unlinked Beeper -> uninstalled Android -> installed and registered signal-cli -> link signal-cli+Beeper. After the last step group messages would show up in signal-cli but not Beeper until the kick/readd step (which only worked after the person doing the kick/readd trusted the new key). 

I don't quite understand why only the linked bridge cared but in it individual messages worked fine yet group did not (even when the person sending had trusted my new key). Untrusted kick/re-add also didn't result in new messages showing up, it took the full trusted + kick/re-add and then everything started flowing (for that group) again.

**Comment by floviolleau** [comment]
Hi,

I followed what is mentionned here: https://gitlab.com/signald/signald/-/issues/336

Hope it will help
