### ISSUE TITLE
Apparently correct homeserver address fails with 404

### ISSUE THREAD

**Issue by kubo6472** [mautrix/signal#269]
![image](https://user-images.githubusercontent.com/26146502/172964267-ae62ae5a-c6f7-4531-bf08-25a89100ec56.png)
What should I put into here?
![image](https://user-images.githubusercontent.com/26146502/172964314-63569f74-ced8-43ce-99f9-df41982acd58.png)
thanks for any help/pointing in the right direction.

**Comment by sumnerevans** [comment]
Can you ping that address from the box you are running the bridge on? Also, if you are using kubernetes, maybe check your networks are configured right so the containers can talk to one another.

**Comment by kubo6472** [comment]
Right now I can't screen the console, but it only says a warning and that it's unreachable on the ip 172.20.0.4, port 443 or smth. I am honestly not sure how exactly to set the port. Conduit's runnung on 6167 and that is exposed from the container, member of the default stack network and another net i made called appservices. By my .well-known I guess it should be reachable on 443, but it isn't, it sorta soft-fails. When specifying the 6167, it does hard 404 and shuts down. As I looked into the configs that worked with synapse and ansible, it uses some nginx proxy in the appservice config instead, and I am running an nginx container for the well-known response. I could theoretically set it up to proxy the traffic from thr conduit container for the appservice container. It definitely is reachable. Thoughit fails where its supossed to work

**Comment by tulir** [comment]
Your conduit is probably outdated

**Comment by kubo6472** [comment]
> Your conduit is probably outdated

Hi, that is definitely not the case, since I started setting it up yesterday and checked that's the latest in fact. Thank you tho. I'll try and debug it some more. Will let you know if any success shall occur.

**Comment by tulir** [comment]
The latest release of conduit is outdated

**Comment by kubo6472** [comment]
> The latest release of conduit is outdated

Oh, alright, so what to use then?

**Comment by kubo6472** [comment]
> The latest release of conduit is outdated

So should I use :next instead?

**Comment by kubo6472** [comment]
It works with :next-alpine and port 6167, thank you very very very very 
very much

**Comment by kubo6472** [comment]
![image](https://user-images.githubusercontent.com/26146502/173133559-90a5495a-645d-4fdb-89b8-72fe81975510.png)
