### ISSUE TITLE
Bridge doesn't set DM avatar

### ISSUE THREAD

**Issue by ItsEcholot** [mautrix/signal#300]
Possibly related to #165.
The difference is that the Username is correctly updated by the bridge after a while but the avatar is never set.
Issuing the `sync` command doesn't change anything.

The following logs are from issuing `sync` from a user that definetly has an avatar set & visible in Signal:
`[2022-08-31 13:30:46,987] [[37mDEBUG[0m@[32mmau.puppet[0m.[[0m] Updating info with Profile(address=Address(number='xxx', uuid=UUID('xxx')), name='Person Name', contact_name='Person Name', profile_name='Name', about='', avatar='', color='', emoji='', inbox_position=0, mobilecoin_address=None, expiration_time=0, capabilities=Capabilities(gv2=True, storage=True, gv1_migration=True, announcement_group=True, change_number=True, sender_key=True, stories=False)) (source: @marc:echolot.io)`

**Comment by KoffeinKaio** [comment]
Got the same problem, signald saves the avatars/group avatars in /signald/avatars but the bridge/synapse/element wont pick them up.

Versions:

```
# docker image ls | grep signal
dock.mau.dev/mautrix/signal                     latest          8a56332d4f88   7 days ago      322MB
signald/signald                                 stable          bbff095c266c   2 weeks ago     204MB
```


docker-compose.yml:
```..yaml
[...]

  signald:
    container_name: signald
    image: signald/signald:stable
    restart: unless-stopped
    environment:
      - "SIGNALD_TRUST_NEW_KEYS=true"
    volumes: 
      - ./data/signald:/signald
    networks:
      - signal

  mautrix-signal:
    container_name: mautrix-signal
    image: dock.mau.dev/mautrix/signal:latest
    restart: unless-stopped
    volumes:
      - ./data/bridges/signal:/data
      - ./data/signald:/signald
    depends_on:
      - signald
    networks:
      - signal
      - matrix


[...]
```

ls from mautrix-bridge (censored):

```
# docker-compose exec mautrix-signal ls /signald/avatars -al
total 1164
drwxrwxrwx    2 1337     1337            15 Sep  7 19:07 .
drwxrwxrwx    6 1337     1337             8 Sep 12 10:37 ..
-rwxrwxrwx    1 1337     1337          3921 Sep  7 19:07 contact-+...
-rwxrwxrwx    1 1337     1337          5197 Sep  7 19:07 contact-+...
-rwxrwxrwx    1 1337     1337          6065 Sep  7 19:07 contact-+...
-rwxrwxrwx    1 1337     1337          4187 Sep  7 19:07 contact-+...
-rwxrwxrwx    1 1337     1337          4645 Sep  7 19:07 contact-+...
-rwxrwxrwx    1 1337     1337         37812 Sep 12 10:38 group-...=
-rwxrwxrwx    1 1337     1337         92418 Sep 12 10:38 group-...=
-rwxrwxrwx    1 1337     1337         83087 Sep 12 10:38 group-...=
-rwxrwxrwx    1 1337     1337        321245 Sep 12 10:38 group-...=
-rwxrwxrwx    1 1337     1337        281684 Sep 12 10:38 group-...=
-rwxrwxrwx    1 1337     1337        123264 Sep 12 10:38 group-...=
-rwxrwxrwx    1 1337     1337         55022 Sep 12 10:38 group-...=
-rwxrwxrwx    1 1337     1337         37386 Sep 12 10:38 group-...=

Bridge config:

```
homeserver:
    address: https://...
    domain: ...
    verify_ssl: true
    asmux: false
    http_retry_count: 4
    status_endpoint:
    message_send_checkpoint_endpoint:
    connection_limit: 100
    async_media: false
appservice:
    address: http://mautrix-signal:29328
    tls_cert: false
    tls_key: false
    hostname: 0.0.0.0
    port: 29328
    max_body_size: 1
    database: postgres://signal:...@postgres/signal
    database_opts:
        min_size: 5
        max_size: 10
    id: signal
    bot_username: signalbot
    bot_displayname: Signal bridge bot
    bot_avatar: mxc://maunium.net/wPJgTQbZOtpBFmDNkiNEMDUp
    ephemeral_events: true
    as_token: ...
    hs_token: ...
metrics:
    enabled: false
    listen_port: 8000
manhole:
    enabled: false
    path: /var/tmp/mautrix-signal.manhole
    whitelist:
    - 0
signal:
    socket_path: /signald/signald.sock
    outgoing_attachment_dir: /signald/attachments
    avatar_dir: /signald/avatars
    data_dir: /signald/data
    delete_unknown_accounts_on_start: false
    remove_file_after_handling: true
    registration_enabled: true
    enable_disappearing_messages_in_groups: false
bridge:
    username_template: signal_{userid}
    displayname_template: '{displayname} (Signal)'
    contact_list_names: prefer
    displayname_preference:
    - full_name
    - first_name
    - last_name
    - phone
    - uuid
    autocreate_group_portal: true
    autocreate_contact_portal: false
    public_portals: false
    sync_with_custom_puppets: false
    sync_direct_chat_list: true
    double_puppet_allow_discovery: false
    double_puppet_server_map:
        ...: https://...
    login_shared_secret_map:
        ...: ...
    federate_rooms: true
    encryption:
        allow: true
        default: true
        require: true
        allow_key_sharing: true
        verification_levels:
            receive: unverified
            send: unverified
            share: verified
        rotation:
            enable_custom: false
            milliseconds: 604800000
            messages: 100
    private_chat_portal_meta: true
    delivery_receipts: false
    delivery_error_reports: true
    message_status_events: false
    resend_bridge_info: false
    periodic_sync: 60
    bridge_matrix_leave: true
    provisioning:
        enabled: true
        prefix: /_matrix/provision
        shared_secret: ...
        segment_key:
    command_prefix: '!signal'
    management_room_text:
        welcome: Hello, I'm a Signal bridge bot.
        welcome_connected: Use `help` for help.
        welcome_unconnected: Use `help` for help or `register` to log in.
        additional_help: ''
    management_room_multiple_messages: false
    permissions:
        '*': relay
    relay:
        enabled: true
        message_formats:
            m.text: '$sender_displayname: $message'
            m.notice: '$sender_displayname: $message'
            m.emote: '* $sender_displayname $message'
            m.file: $sender_displayname sent a file
            m.image: $sender_displayname  sent an image
            m.audio: $sender_displayname  sent an audio file
            m.video: $sender_displayname  sent a video
            m.location: $sender_displayname  sent a location
        relaybot: '@relaybot:example.com'
    location_format: https://www.google.com/maps/place/{lat},{long}
logging:
    version: 1
    formatters:
        colored:
            (): mautrix_signal.util.ColorFormatter
            format: '[%(asctime)s] [%(levelname)s@%(name)s] %(message)s'
        normal:
            format: '[%(asctime)s] [%(levelname)s@%(name)s] %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: colored
    loggers:
        mau:
            level: WARN
        aiohttp:
            level: WARN
    root:
        level: WARN
        handlers: [console]
```

**Comment by sumnerevans** [comment]
@thefinn93 probably fixed this in https://gitlab.com/signald/signald/-/commit/2b81973c4301fde34a4cd109902a1f4b04342fe1

**Comment by mackshot** [comment]
I can confirm that updating to the latest signald version fixes the problem.
