### ISSUE TITLE
Release of "Creating Group Command" Feature

### ISSUE THREAD

**Issue by aimanabdou** [mautrix/signal#302]
I tried out the current signal bridge in the master branch and found out that you could add Signal groups since May 13, 2022 (Commit: https://github.com/mautrix/signal/commit/1be53a2f0f5bad4d8cb18eb729556374cc728683?diff=split). This feature is unfortunately missing from the current version v0.3.0 release. 

Are there any plans on when this feature is going to be released?

Thank you in advance. 😁

**Comment by tulir** [comment]
Releases happen occasionally, but they're not planned

**Comment by aimanabdou** [comment]
Okay, thank you @tulir for the quick response. 😁
