### ISSUE TITLE
messages sent via mautrix-bridge to signal group are not sent to others

### ISSUE THREAD

**Issue by xundeenergie** [mautrix/signal#313]
When i send via element or schildi a message to a signal group, the message does not reach the others in the group.

I have double-puppeting activated.

When i send the message from matrix, i can receive it on my android client and on my desktop-client. 
I get this in the logfiles for mautrix bridge and signald on sending
```
Oct 14 12:20:55 sc-chat-01 mautrix-signal[810136]: [2022-10-14 12:20:55,780] [INFO@mau.portal.AGOsblafoblafoblafoblafooblafooOElL8W/xJvQc=] Send attempt 0. Attempting to send $7RTDaBuWK_pfiHzJ9BhzYsHOmb1xNXtozNRu-lRj6gw with d7e45881-bfd7-4ae5-95bd-d0d9a94d3389
Oct 14 12:20:56 sc-chat-01 signald[810097]: 12:20:56.647 [d7e45881-bfd7-4ae5-95bd-d0d9a94d3389-send] INFO  send - handled request d7e45881-bfd7-4ae5-95bd-d0d9a94d3389 successfully
Oct 14 12:20:56 sc-chat-01 mautrix-signal[810136]: [2022-10-14 12:20:56,648] [INFO@mausignald] Successfully sent message to 2/2 users in AGOsblafoblafoblafoblafooblafooOElL8W/xJvQc= with 0 unregistered failures
```
but the other 2 members of the signal-group never get the message.

Sometimes restarting the bridge is enough, sometimes i have to leave the signal room and get invited back....

I started signald with "-v" for verbos output and got a LOT of lines

`DEBUG io.finn.signald.jobs.RefreshProfileJob - refusing to refresh the same profile too frequently"

Maybe this is problematic and a reason for not sending the messages to the other member?

**Comment by Gymnae** [comment]
+1 facing the same issue. But not only with groups. Occasionally, I see only the incoming messages in the official signal iOS client and not what I wrote, but the other party sees both sides of the thread. Some messages sent via signal don't arrive in matrix. I'm not sure what is going on, but these two issues might be related to the group issue described in OP
