### ISSUE TITLE
Hide bot messages in room

### ISSUE THREAD

**Issue by tzugen** [mautrix/signal#315]
Hi!
I have a bridged room, and users are often getting confused by the bot messages.
Can I tell the bot to only communicate in the notice room?

**Comment by tulir** [comment]
What messages?

**Comment by tzugen** [comment]
For example it spammed the room with errors about a certificate.

**Comment by tulir** [comment]
https://github.com/mautrix/signal/blob/master/mautrix_signal/example-config.yaml#L225-L226
