### ISSUE TITLE
Suddenly getting this error: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by undercoverturbo** [mautrix/signal#316]
Hi,

I am running a Matrix Server, using the ansible playbook. Everything was working fine, now the signal bridge suddenly throws this error, when trying to bridge a message from Matrix to Signal:

> Your message was not bridged: InternalError: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException, [javax.net](http://javax.net/).ssl.SSLHandshakeException, [sun.security](http://sun.security/).validator.ValidatorException, [sun.security](http://sun.security/).provider.certpath.SunCertPathBuilderException: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: [javax.net](http://javax.net/).ssl.SSLHandshakeException: PKIX path building failed: [sun.security](http://sun.security/).provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I can't find anything helpful on the Internet.

What does this error mean and how do I fix it?

Thanks,
Jan

P.S.:
When bridging a portal that already exists to another Matrix room, after the continue-and-delete confirmation, while Clening up, the Signal bridge threw this error every time:
> Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 491, in confirm_bridge
    await _locked_confirm_bridge(
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 517, in _locked_confirm_bridge
    (
ValueError: too many values to unpack (expected 5)

It still worked, though.

**Comment by tulir** [comment]
Update signald (and also the bridge)

**Comment by undercoverturbo** [comment]
Sorry for that, I thought I already updated the bridge, but the update did not work. Now that I have successfully updated the bridge, everything is back in working order.
Thanks for all your efforts!
