### ISSUE TITLE
Other signal users can not add bridged user to groups

### ISSUE THREAD

**Issue by domi0003** [mautrix/signal#32]
When other Signal (Android - v5.0.8) users try to add the bridged user to a group chat, they get a response, that "The signal app of the added user does not support the newest version of group conversations and has to be updated".
This happens as long as the the bridge is a linked device. When the bridge is unlinked, other users can again add you to the group chat. The same behavior also happens if the bridge is the primary registered device.

**Comment by 8cH9azbsFifZ** [comment]
Once I am added to a "new" group in Signal (after Unlinking the Bridge) I cannot link the Bridge to my Signal account any more.

**Comment by tulir** [comment]
Are you using an up-to-date version of signald?

You can check the `gv2` capability flag with `!signal raw --user get_profile {"recipientAddress": {"number": "+1234567890"}}` and if it's false, `!signal raw --user refresh_account {}` should fix it. It should be true by default for newly linked devices, but it's possible there's a bug somewhere.

**Comment by 8cH9azbsFifZ** [comment]
`docker ps` shows `dock.mau.dev/maunium/signald:latest`. I cannot use the command above, as linking to my signal account again fails: 
`Unhandled error while handling command. Check logs for more details (ref. XXXX)`

**Comment by domi0003** [comment]
Running the `!signal raw --user ...` commands results in `This command requires administrator privileges`.
signald also running in container with latest docker tag, output of `signald --version` results in `signald unversioned`.

Found the following files in `/opt/signald/lib` - maybe that helps to identify the version:
```
-rw-r--r-- 1 root root  263184 Jan 11 04:29 signald.jar
-rw-r--r-- 1 root root   63345 Jan 11 04:28 signal-metadata-java-0.1.2.jar
-rw-r--r-- 1 root root  269033 Jan 11 04:28 signal-protocol-java-2.8.1.jar
-rw-r--r-- 1 root root 1540003 Jan 11 04:28 signal-service-java-2.15.3_unofficial_15.jar
```

**Comment by tulir** [comment]
`docker ps` won't show if it's the latest version, only `docker pull <image>` does. You can edit the config to become administrator.

**Comment by 8cH9azbsFifZ** [comment]
Sure ;) 

> `docker ps` won't show if it's the latest version, only `docker pull <image>` does. You can edit the config to become administrator.

Sure ;) > docker pulled the latest image before, of course (as of yesterday).
