### ISSUE TITLE
New signal safety number is not recognized by the bridge 

### ISSUE THREAD

**Issue by justusweigmann** [mautrix/signal#323]
A friend has changed his number on Signal, which has changed his safety-number. However, this number is not transferred to the bridge either during a complete sync of the bridge or during a manual verify. Even deleting the chat and reopening it did not solve the problem. This means that the messages sent via Matrix cannot be read. Does anyone else has the same problem or has a solution?

**Comment by sumnerevans** [comment]
If you delete the rows associated to the distribution ID for that chat from the `sender_key_shared` and `sender_keys` tables in the signald database, do messages start working again?

**Comment by shukon** [comment]
Workaround could be accepting all security keys on bridge start-up using [signald-env-variables to trust all keys](https://signald.org/articles/config/)?

**Comment by recklesscoder** [comment]
I think I have the same problem: a friend's safety number changed and now any messages sent to them from Matrix don't arrive and only have one gray checkmark when viewed in an official Signal app. In groups, messages are still delivered correctly to everybody else. My friend is only using official Signal apps, and when I send messages from an official Signal app they arrive fine.

One thing I have noticed is that the safety number displayed when using the `safety-number` command with the Signal bridge bot does not match the safety number displayed in the official Signal app and on my primary device (which is a completely separate instance of signal-cli and signald). It might also be worth noting, that messages sent from that signal-cli instance also arrive fine.

I have tried out @sumnerevans's proposed solution but to no avail. Some of the deleted rows have been regenerated by sending in those groups, but messages are still not delivered to my friend, neither in groups nor in private chat.

The trust level for the contact in question appears as `TRUSTED_UNVERIFIED`, but that is also the case for other contacts who still correctly receive messages from Matrix.

I'm using mautrix-signal as part of the [spantaleev/matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) Ansible playbook, leaving their suggested settings for mautrix-signal entirely untouched. The logs for the signald container contain nothing but success messages and the logs for the mautrix-signal container only contain a few warnings emitted during startup.

Let me know if there is something else I should try or somewhere else I should look.

**Comment by recklesscoder** [comment]
Thanks for providing the proper way to trust all keys using the playbook's variables, but alas, it did not help with the problem at hand. The security number displayed by the `safety-number` command is still incorrect and messages still don't arrive.

The log shows these two new lines, which lead me to believe the environment variables did take effect:
```
[main] INFO  io.finn.signald.db.sqlite.IdentityKeysTable - marking all currently UNTRUSTED keys in as TRUSTED_UNVERIFIED for all accounts
[main] INFO  io.finn.signald.db.sqlite.IdentityKeysTable - marked 0 key(s) as TRUSTED_UNVERIFIED
```

I can only conclude that "trust" is not the issue.
