### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by tzugen** [mautrix/signal#324]
It would be nice to have a documentation of all possible commands.
!signal help doesn't show them all, for example `invite-link` is not mentioned

**Comment by tulir** [comment]
The help shows everything, but it excludes ones you can't use

**Comment by tzugen** [comment]
Then it excludes the wrong ones.

**Comment by tzugen** [comment]
Any way either way I think the request to improve the docs is valid. Obviously people are getting confused.
