### ISSUE TITLE
Messages of some users are ignored.

### ISSUE THREAD

**Issue by tzugen** [mautrix/signal#325]
We have a Element space with a bunch of rooms, each with a signal portal.
Things work mostly fine, except in one room, messages of some users are never sent to the portal.
In the logs it says:
```
mautrix-signal    | [2022-11-25 19:55:00,849] [DEBUG@mau.mx] Received Matrix event $EjzyJfGindJiz7xk3S4PW9kU13lQ1L4vTLkn6aKRYP4 from @xxxxxxxxxxxxx in !ATvxdkXKQywgNdkQAZ:xxxxxxxxxxx
mautrix-signal    | [2022-11-25 19:55:00,850] [DEBUG@mau.mx] Ignoring event $EjzyJfGindJiz7xk3S4PW9kU13lQ1L4vTLkn6aKRYP4 from @xxxxxxxxxxxxxxxx: not allowed to send to portal
```

**Comment by tulir** [comment]
Does the portal have relay mode enabled?

**Comment by tom-ch1** [comment]
I also have this issue. relay-mode is enabed. It was triggered by an update of synapse (from 1.71 to 0.89 on debian bullseye) and an update of the signal bridge from 2023-06-30 to 2023-08-13 (which may not even have been an update).
After that, I receive the same error as the original poster for any message sent from telegram or whatsapp ghost users into a matrix room which is relayed to signal

**Comment by tom-ch1** [comment]
In my case, the reason was that for whatever reason, the relay state was forgotten by the bridge.
`!sig unset-relay` resulted in `This room does not have a relay user set.`
a `!sig set-relay` resolved my issue
