### ISSUE TITLE
Reactions to captioned Signal photos are not bridged

### ISSUE THREAD

**Issue by meson800** [mautrix/signal#330]
When photos are sent through the Signal client with a caption (as a single message), this single message gets turned into two messages in the bridged Matrix room, one for the photo and one for the caption.

Reacting to the _photo_ message leads to a "Your reaction was not bridged: Could not find message to react to on Signal." error. Responding to the caption message leads to a successfully bridged reaction that appears on the captioned picture in Signal. The relevant logs are:
```
mautrix-signal         | [2022-12-20 02:42:14,640] [INFO@aiohttp.access]  [20/Dec/2022:02:42:14 +0000] "PUT /transactions/437084?access_token=---snip--- HTTP/1.1" 200 159 "-" "Synapse/1.70.0"
mautrix-signal         | [2022-12-20 02:42:14,640] [INFO@mau.portal.---snip---] Send attempt 0. Attempting to send $T_Bd-qIp---snip--- with 1b0abd82----snip---
mautrix-signal         | [2022-12-20 02:42:14,641] [DEBUG@mau.portal---snip---] Ignoring reaction to unknown event $aYxhgIXD_---snip---
mautrix-signal         | [2022-12-20 02:42:14,641] [ERROR@mau.portal.---snip---] UnknownReactionTarget: Going to sleep for 1s. Error: Ignoring reaction to unknown event $aYxhgIXD---snip---
mautrix-signal         | Traceback (most recent call last):
mautrix-signal         |   File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 547, in _signal_send_with_retries
mautrix-signal         |     await send_fn(sender, event_id, req_id=req_id, **send_args)
mautrix-signal         |   File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 634, in _handle_matrix_reaction
mautrix-signal         |     raise UnknownReactionTarget(f"Ignoring reaction to unknown event {reacting_to}")
mautrix-signal         | mautrix_signal.portal.UnknownReactionTarget: Ignoring reaction to unknown event $aYxhgIXD_---snip---

--- four more send attempts before ---

mautrix-signal         | Traceback (most recent call last):
mautrix-signal         |   File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 592, in handle_matrix_reaction
mautrix-signal         |     retry_count = await self._signal_send_with_retries(
mautrix-signal         |   File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 580, in _signal_send_with_retries
mautrix-signal         |     raise last_error_type(f"Failed to send {event_type_name} after {retry_count} retries.")
mautrix-signal         | mautrix_signal.portal.UnknownReactionTarget: Failed to send reaction after 4 retries.
```

**Comment by rufflepot** [comment]
I noticed this as well recently and figured the text part (when one is included in the message send from Signal) is the actual message as interpreted by mautrix-signal. I had forgotten all about this but I'm glad you made an Issue with logs.

**Comment by meson800** [comment]
Yes, I agree. In the handle message code, each attachment gets [sent as it's own Matrix message](https://github.com/mautrix/signal/blob/master/mautrix_signal/portal.py#L1275-L1283), which also sets the `event_id` key. Then, the caption text gets [sent](https://github.com/mautrix/signal/blob/master/mautrix_signal/portal.py#L1286-L1294), also updating the `event_id` variable. Finally, the `event_id` message [gets inserted into the database](https://github.com/mautrix/signal/blob/master/mautrix_signal/portal.py#L1296-L1305) that records which Matrix message matches which Signal message. In the case of attachments, this means only the text part is linked to the Signal message.

I'm not entirely sure what the desired behavior is here. One approach would be to link the reactions to any attachment and/or caption together, so that reacting to one reacts to all of them. This would lead to a lot of duplicate linked reaction spam on the Matrix side though. Maybe there's an intermediate way where Matrix reacts are not duplicated over all relevant Matrix messages, but they are combined on the Signal side?

**Comment by sumnerevans** [comment]
The real solution would be to implement support for https://github.com/matrix-org/matrix-spec-proposals/pull/2530 and/or https://github.com/matrix-org/matrix-spec-proposals/pull/3552, but not many clients support either of those. Bridges like Instagram already support these MSCs (https://github.com/mautrix/instagram/pull/58) so that same general approach could be ported over to Signal as well.

**Comment by meson800** [comment]
I didn't know that existed! It looks like matrix-org/matrix-spec-proposals#2530 would only support single-image captions, though it looks like the full extensible events in matrix-org/matrix-spec-proposals#3552 would [possibly](https://github.com/matrix-org/matrix-spec-proposals/pull/3552#discussion_r1057491424) allow entire album messages to be linked, as Signal does.
