### ISSUE TITLE
Creating Signal room fails when room is untitled (mausignald.errors.RequestValidationFailure: missing required argument: title)

### ISSUE THREAD

**Issue by jakecoppinger** [mautrix/signal#341]
Steps to reproduce:
- Create Matrix room
- Add Signal bot
- Make Signal bot admin
- `!signal create`

I assume the bridge uses the room title to create the Signal chat, and when it doesn't exist throws an exception. Should the fix be setting the room display name like element does - by enumerating the names of the people in the chat?

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/commands/signal.py", line 356, in create
    await portal.create_signal_group(evt.sender, levels, join_rule)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 1787, in create_signal_group
    signal_chat = await self.signal.create_group(
  File "/opt/mautrix-signal/mausignald/signald.py", line 439, in create_group
    resp = await self.request_v1("create_group", account=username, **create_params)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 244, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 238, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 235, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.RequestValidationFailure: missing required argument: title
```

Issue mitigated by setting a room name.

**Comment by tulir** [comment]
Setting a room name is required (and is already validated: https://github.com/mautrix/signal/commit/c2248c48863915f065c21d62998d8d4e56d1a26c)

**Comment by jakecoppinger** [comment]
Thanks! I must have an old version on my homeserver.

**Comment by maltee1** [comment]
Can we assign a default name, such as "Bridged Matrix room !abcde:example.org" or "User1, User2 and 4 others" if no room name is set on matrix? I prefer reasonable fallbacks over errors.

**Comment by jakecoppinger** [comment]
> "User1, User2 and 4 others"

I like this - so it matches the behaviour of Element and doesn't require all group "dm" chats to require a name. If the user does want to set a room name I assume the bot will rename the Signal chat?

**Comment by maltee1** [comment]
Well, the problem with this approach is that the signal chat would have to be renamed every time a user joins or leaves, so it's probably not a good idea. I just mentioned it because it's common behaviour on many chat platforms. The disadvantage of the other approach is that it doesn't make much sense to a signal user.

**Comment by tulir** [comment]
It's definitely not going to be renamed automatically. Something generic like "Unnamed group" might be fine though, along with setting the same name for the Matrix room and sending a warning message so that it's clear that it happened.

**Comment by maltee1** [comment]
I agree that continuous renaming is probably a bad idea.

The room name should remain empty. Renaming the room would have to be relayed to other bridges, which many do not support. Those bridges might then attempt to set an empty room name again, if the remote platform supports it. Or, if fallback names are different, different bridges might ping pong fallback names.

We also need to not set a room name upon sync, if the room name is empty and the signal side group name is equal to the fallback.
