### ISSUE TITLE
Wrong puppet names (mixed up / shuffled)

### ISSUE THREAD

**Issue by Zocker1999NET** [mautrix/signal#343]
I have a weird error and I see no way to fix it other than maybe fully re-setup the whole bridge. The signal bridge messed up the names of most users.

Example: I know 5 users using Signal called Alpha, Beta, Gamma, Delta, Epsilon. Alpha wrote me (e.g. "Hi, I'm Alpha"). The bridge creates a new DM room with a puppet called Gamma writing "Hi, I'm Alpha" (thats how I discovered the bug). The same happens in groups. The puppet's avatars are correct though and help me identify the other users. Beta then may be called Delta, Gamma is called Beta, etc.

I started using mautrix-signal probably at version 0.4.0 (sadly, I do not know due to #344). I now upgraded to 0.4.2 (with signald 0.23.1) and tried so far:
- use the `sync` command
- let my 2nd signal account change its name
- restart the bridge (serveral times; with signald restarted as well)

I want to avoid recreating all the rooms, but I would be ready to resetup signald (even manually so the bridge reconnects it with the already existing rooms).

Is there a way to manually force syncing the names? Or is this more likely an issue with signald?
I'm ready to supply more info / logs if requested and to help to find the reason for this bug (if not already fixed).

**Comment by sumnerevans** [comment]
Possibly related signald issue: https://gitlab.com/signald/signald/-/issues/356
