### ISSUE TITLE
Log version number when starting

### ISSUE THREAD

**Issue by Zocker1999NET** [mautrix/signal#344]
Quite a small one: Log the version number when the bridge is starting, because:
- it helps when reading all logs to know which version was that
- and (because of that) it is considered good practice
- it has nearly no disadvantages except producing a few bytes more log (which can be compressed away)

**Comment by tulir** [comment]
It's already logged 🤔

![image](https://user-images.githubusercontent.com/4224639/219949045-92b041f4-b33c-4f05-9d3d-d087b0c769cb.png)

**Comment by Zocker1999NET** [comment]
Oh, maybe its the level of logging? It seems that the version number is logged as  INFO for you.
matrix-docker-ansible-deploy (which I use) defaults to logging level WARNING: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/30185a04e90d7a1b7964450edb9d9d8360829ac6/roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml#L67

Would it be feasible to log the version number ignoring the logging level?
I think it would be worth enough comparing its usefulness to the added cost of storage.
