### ISSUE TITLE
hcpatcha

### ISSUE THREAD

**Issue by Thatoo** [mautrix/signal#358]
I can't register using hcaptcha provided by https://signalcaptchas.org/registration/generate.html

I have tried this three method
```
register --captcha signal-hcaptcha.<token> <phone number>
!signal register --captcha signal-hcaptcha.<token> <phone number>
register <phone number> --captcha signal-hcaptcha.<token>
```
but I always get this error : 
`Unhandled error while handling command. Check logs for more details (ref: 1673175080).`
I don't know how to get recaptcha v2 anymore sot I don't know how to register a phone number.

**Comment by tulir** [comment]
Probably either a setup issue or a signald issue, but even if it's a bridge issue it's not going to be fixed in this version.
