### ISSUE TITLE
[Question] Moved to new phone - groups is not sync anymore what should I do? 

### ISSUE THREAD

**Issue by floviolleau** [mautrix/signal#365]
Hi,

Thanks for your support here.

I use:
mautrix-signal: 0.4.3
signald: 0.23.1

If I do `clean-rooms` command, I have this output
```
Management rooms (M)
1. Signal Bot
2. Signal Bridge

Active portal rooms (A)
No active portal rooms found.

Unidentified rooms (U)
1. group A
2. group B
3. group C
[...]

Tombstoned rooms (T)
No tombstoned rooms found.

Inactive portal rooms (I)
No inactive portal rooms found.

Usage
To clean the recommended set of rooms (unidentified & inactive portals), type clean-recommended

To clean other groups of rooms, type clean-groups <letters> where letters are the first letters of the group names (M, A, U, I, T)

To clean specific rooms, type clean-range <range> where range is the range (e.g. 5-21) prefixed with the first letter of the group name. (e.g. I2-6)

Please note that you will have to re-run clean-rooms between each use of the commands above.
``` 

It seems that the room in matrix is not linked anymore to the signal group. Maybe due to the fact that I installed a fresh version of signal on my new phone without using backup and did a logout / login in portal matrix room. 

I see that there is a command:
`bridge <signal chat ID> [matrix room ID] - Bridge the current Matrix room to the Signal chat with the given ID.`

How can I get the `signal chat ID`?

I tried as well in this order to:
- `logout`
- stop mautrix-signal
- stop signald
- mv signal_data signal_data.old
- clear mautrix-signal DB (did a backup before)
- start signald
- start mautrix-signal
- `login`

Thanks for your help

**Comment by bendschs** [comment]
same here

**Comment by floviolleau** [comment]
Hi,

I moved to raspbian 64bits so I 'm able to upgrade to latest signald 0.23.1 and it is working fine now
