### ISSUE TITLE
Messages from matrix to signal do not get transported if room in signal has only me as member

### ISSUE THREAD

**Issue by c-holtermann** [mautrix/signal#370]
There are some rooms where I am the only member. I.e. one to store notes. Or I have set some up to check different bridging approaches. Messages get transferred from signal to connected matrix rooms. The matrix rooms can have different numbers of users. It took me some time to figure out that this issue of not relaying messages from matrix to signal is related to the number of users in signal being one.

Having a look into the log files of mautrix-signal i saw this:

In a group with at least one other aside from myself it shows:
```
"[INFO@mausignald] Successfully sent message to 1/1 users in y0HjE+o3t9NqJdsD897aUiwULr9NKrLju7j3+1O9NAk= with 0 unregistered failures"
```
In a group where I am the only user it shows:
```
 "[INFO@mausignald] Successfully sent message to 0/0 users in y0HjE+o3t9NqJdsD897aUiwULr9NKrLju7j3+1O9NAk= with 0 unregistered failures"
```
so obviously I am not counted as a member of the group. The message gets sent to signal but there is no user to send it to. Thinking about this some more I realized that messages in groups with more members than myself show like they are being sent by myself. So as my signal personality is sending the relayed messages from a certain perspective it makes sense that it does not send messages to itself. So this might be a feature and not a bug but it is something I did not expect. I don't know if all the bridges behave like this. Either this could be changed or it might make sense to mention it in the docs. It means that in rooms where I am the only person I need to somehow create another account to relay my matrix-messages/notes to my-signal-self.

I have tried this without and with double puppeting and tried "!signal set-relay". I am running a current docker deployment which should be 0.4.3.

**Comment by rthouvenin** [comment]
I also got the same problem while testing bridging between Whatsapp and Signal. This occurs only for the Signal relay. On Whatsapp, I receive the relay messages even if I am alone in the group.
