### ISSUE TITLE
Add support for Text Effects

### ISSUE THREAD

**Issue by mattcen** [mautrix/signal#373]
on 2023-06-24 I received this message from Signal in-app (though I've not found documentation for it anywhere on the web yet):
![](https://github.com/mautrix/signal/assets/4273659/7c56a36e-1244-4830-bc99-d66b459f8a43)
> **Text effects**
> 
> Format text in your messages by selecting any text in the message composition field.
> 
> Make a **bold** statement that's actually bold, send M. Night Shyamalan a twist ending with a spoiler <details><summary>spoiler</summary>effect</details>, emphasize a name by writing "*Alex*" in italics, put a line through a ~~rejected~~ dinner idea with strikethrough, or share code in `monospace`.

It'd be great if this support were available through the bridge, too, since Matrix supports all of these (well, most, since spoilers are message-wide in Matrix)

**Comment by mattcen** [comment]
Ref: https://github.com/signalapp/Signal-Android/commit/882748f

**Comment by tulir** [comment]
Formatting will obviously be supported, but not in the Python version.

> since spoilers are message-wide in Matrix

(spoilers are not message-wide in Matrix, they're HTML tags just like all other formatting)

**Comment by mattcen** [comment]
Awesome! I guess I'd misunderstood spoilers and conflated them with how Element behaves by default. Thanks for mentioning this though; I've now worked out how to create spoiler segments in Element :)
(for anyone wondering: `/html This is a <span data-mx-spoiler>Spoiler</span> test`)
