### ISSUE TITLE
Pictures are not received nor backfilled

### ISSUE THREAD

**Issue by mietzen** [mautrix/signal#374]
I recently setup the mautrix signal bridge and been playing around with it a couple of days. 
I set up double puppeting via [matrix-synapse-shared-secret-auth](https://github.com/devture/matrix-synapse-shared-secret-auth), and followed the instructions given in: https://docs.mau.fi/bridges/general/double-puppeting.html

I noticed some unexpected behaviour:

- I received a messages with pictures in a group chat that wasn't displayed 
- I sent Pictures via signal (directly via iOS app) which also weren't backfilled to the bridge.

Text messages work without problem.
I couldn't find any limitations regarding pictures, sending them directly via element also works.

**Comment by maltee1** [comment]
You should probably have a look at #372
