### ISSUE TITLE
Signal Bridge Update - Mismatching Application Service ID Error

### ISSUE THREAD

**Issue by justusweigmann** [mautrix/signal#380]
I recently updated my Signal Bridge after some time and ensured to create a backup beforehand. Without modifying any configurations or settings, I proceeded to update by pulling the new image via Docker Compose. However, post-update, the Bridge is throwing the following error: mautrix.errors.request.MForbidden: Mismatching application service ID in path. The Homeserver is also providing a corresponding error: SynapseError: 403 - Mismatching application service ID in path. The error log is as follows:

2023-11-16 09:00:28,094 - synapse.http.server - 124 - INFO - POST-284 - <XForwardedForRequest at 0xffff819c51d0 method='POST' uri='/_matrix/client/v1/appservice/signal/ping?user_id=@signalbot:mydomain.com' clientproto='HTTP/1.1' site='8008'> SynapseError: 403 - Mismatching application service ID in path

Has anyone else encountered a similar issue during the Signal Bridge update? Any assistance or insights into resolving this problem would be greatly appreciated.

**Comment by tulir** [comment]
That error means the registration yaml and bridge config have different appservice IDs (`id` in registration, `appservice`->`id` in config)
