### ISSUE TITLE
Double puppeting not working anymore with Go Signal bridge (docker)

### ISSUE THREAD

**Issue by pbek** [mautrix/signal#382]
Thanks for this great bridge, which I enjoy using every day!

A few hours ago, the docker image with the go implementation (see #372) got pushed to https://mau.dev/mautrix/signal/container_registry/47.

This of course immediately broke my bridge, because of missing settings. 😉 
After fixing the `config.yml` I was able to talk to the bridge via my Synapse server again, but double puppeting is not working anymore.
I still have my `registration.yaml` in place for the bridge and the Synapse server.

I'm getting errors like this:

```
2023-12-18T13:13:13Z WRN Failed to login with shared secret error="failed to POST /_matrix/client/v3/login: M_FORBIDDEN (HTTP 403): Invalid username or password" user_id=@user:domain.com

2023-12-18T12:34:43Z ERR problem looking up aci 0c0bec05-bab5-4582-81ec-178428726c9b error="failed to scan session: 40: no key type identifier" user_id=@user:domain.com

2023-12-18T12:33:17Z ERR Failed to start custom puppet error="failed to POST /_matrix/client/v3/login: M_FORBIDDEN (HTTP 403): Invalid username or password" signal_user_id=0c0bec05-bab5-4582-81ec-178428726c9b

2023-12-18T13:22:19Z WRN Failed to login with shared secret error="failed to POST /_matrix/client/v3/login: M_LIMIT_EXCEEDED (HTTP 429): Too Many Requests" user_id=@user:domain.com
```

Note: I replaced my actual username with `user:domain.com` in above logs.  

Does anyone have an idea what went wrong?

**Comment by pbek** [comment]
My `registration.yaml` looks like this:

```
id: signal
as_token: secret
hs_token: secret
namespaces:
    users:
    - exclusive: true
      regex: '@signal_.*:domain\.com'
    - exclusive: true
      regex: '@signalbot:domain\.com'
    aliases: []
url: http://mautrix-signal:29328
sender_localpart: secret
rate_limited: false
```

**Comment by pbek** [comment]
I added this part:

```yaml
  - regex: '@.*:domain\.com'
    # This must be false so the appservice doesn't take over all users completely.
    exclusive: false
```

... and bridging seems to work again. 🤔

**Comment by pbek** [comment]
Thank you for the feedback, @pm-McFly. I have some other weird issue too now. In Element for Android, I cannot see the text in replied messages anymore for all new messages since my bridge went up again. Element Web works fine. Have you had that issue, or is it just me?

**Comment by pbek** [comment]
But I can see the replies in your screenshot, for me, I just see that the other person replied to a message, but I can't see the text, like the `Done` on your `Okay`.

**Comment by tulir** [comment]
Looks like the original issue was already resolved. Element Android doesn't support rendering replies correctly, using another client like SchildiChat, FluffyChat or Element X is recommended

**Comment by pbek** [comment]
> Element Android doesn't support rendering replies correctly

Really? I didn't know that and I didn't have any issues with the python signal bridge, the telegram bridge, the whatsapp bridge or the facebook bridge.

**Comment by pbek** [comment]
> I suggest opening another issue dedicated to this behavior as the initial inquiry here is not related to it directly.

I now did (#384).
