### ISSUE TITLE
"Failed to parse config: username template is missing user ID placeholder"

### ISSUE THREAD

**Issue by hagelschaden** [mautrix/signal#385]
Hello there!

I'm using the official docker image which apparently got updated yesterday. I'm now getting this error in the logs:

`Failed to parse config: username template is missing user ID placeholder`

When I downgrade by setting the "v.0.4.3" tag I get a new error:

`[2023-12-19 08:11:12,981] [INFO@mau.init] Initializing mautrix-signal 0.4.3
[2023-12-19 08:11:12,981] [CRITICAL@mau.init] Unexpected error in initialization
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/util/program.py", line 101, in _prepare
    self.prepare()
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 130, in prepare
    self.prepare_db()
  File "/usr/lib/python3.10/site-packages/mautrix_signal/__main__.py", line 59, in prepare_db
    super().prepare_db()
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 192, in prepare_db
    self.db = Database.create(
  File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/database.py", line 66, in create
    url = URL(url)
  File "/usr/lib/python3.10/site-packages/yarl/_url.py", line 154, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str`

**Comment by tulir** [comment]
The error means the `username_template` is wrong, although not exactly sure how that would happen since the migration automatically upgrades the template

**Comment by hagelschaden** [comment]
Any idea how I could fix this. Do I have to change something in the config.yml? Apparently after the switch to go things have changed but I cannot find infos on what exactly I have to change..

**Comment by tulir** [comment]
First probably check if it works automatically by upgrading to the latest version. If not, look at what the current `username_template` is, post it here, then change it to have the same kind of placeholder as the example https://github.com/mautrix/signal/blob/main/example-config.yaml#L90

**Comment by tulir** [comment]
Maybe try the `:6e7faa2a6583ab324826e1c1d9e34794abfafb9f-amd64` tag to make sure it's actually latest and not an old version of latest

**Comment by hagelschaden** [comment]
That solved it thanks!!

Well I still had to figure out that for some bizzare reason my postgres-credentials were deleted from the config during the failed upgrade I presume. So i filled those in again.

And then of course I had to link signal again.

**Comment by tulir** [comment]
Database config being removed was probably the same old version issue (config migration was only added yesterday, so if you pulled 2 days ago it wouldn't automatically migrate)
