### ISSUE TITLE
Don't "downgrade" displaynames

### ISSUE THREAD

**Issue by maltee1** [mautrix/signal#396]
The go bridge seems to be suffering from the same problem the python bridge suffered from: renaming of users on every sync. For now I can only see users being renamed back and forth between phone number and profile name, so a good first measure might be to not downgrade a name, i.e. not rename to a phone number if the current one is a profile name.
I can't yet tell whether some profile name information will eventually lose sync between different bridge users, I guess I'll wait and file another bug report in that case.

**Comment by maltee1** [comment]
I think this was solved with "name quality" in the python bridge, but I think a more straightforward way would be to just store the profile name and check if it's empty - in that case, just use the previously known profile name.

**Comment by tulir** [comment]
Name quality is probably required, possibly even more complicated than the python bridge. It should include the profile fetch timestamp or some other version identifier for the profile name.

**Comment by maltee1** [comment]
This appears to affect avatars, too. While re-setting the same avatar seems fixed, I'm still seeing avatars being removed and re-set.

Is it possible that contact info is sometimes empty and not updating empty contact info would already solve the problem? Maybe checking for empty profileKey or something would work?

**Comment by AndrewFerr** [comment]
> Is it possible that contact info is sometimes empty and not updating empty contact info would already solve the problem? Maybe checking for empty profileKey or something would work?

What can happen is that the contact info isn't _entirely_ empty, but fields that had been filled on an earlier fetch are empty on a later fetch.  For example, a fetched info can have all but its phone number be empty, even if an earlier fetch included a profile name.

**Comment by maltee1** [comment]
I figured out the issue for profile names in my particular case I think. It seems the bridge attempts to sync profiles regardless of whether a profile key is available or not (`profile_key == \x` in the database). If a bridge user has someone in their contact list but hasn't spoken to them, their profile will return empty. If someone else has their profile key and can therefore get their profile name, the bridge will toggle between name and phone number.

It probably doesn't make sense to attempt fetching profiles if no profile key is available. Disabling that should significantly improve the situation.
