### ISSUE TITLE
Error when logout and then login again

### ISSUE THREAD

**Issue by Yajo** [mautrix/signal#41]
1. register
2. logout
3. link
4. scan code on phone
4. logout
5. link
6. scan code on phone
6. error

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/auth.py", line 65, in link
    account = await evt.bridge.signal.link(callback, device_name=device_name)
  File "/opt/mautrix-signal/mausignald/signald.py", line 114, in link
    raise make_linking_error(resp)
mausignald.errors.LinkingConflict: The user +********* already exists. Delete "/signald/data/+***********" and trying again.
```

**Comment by tulir** [comment]
This is expected if you haven't configured [`signal`->`data_dir`](https://github.com/tulir/mautrix-signal/blob/master/mautrix_signal/example-config.yaml#L69-L70) properly

**Comment by Yajo** [comment]
I guess that should be done automatically by matrix-docker-ansible-deploy right?

**Comment by joao-p-marques** [comment]
The Ansible Playbook uses the docker image and AFAICS the config looks correct when comparing it to [the instructions](https://github.com/tulir/mautrix-signal/wiki/Bridge-setup-with-Docker#setup): https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-bridge-mautrix-signal/templates/config.yaml.j2#L77

Is something wrong? Maybe the instructions were misunderstood and the `data` config should be left with the original value?

**Comment by Yajo** [comment]
I guess the issue should be moved there then. It may be related with permissions among containers and UIDs/SELinux?

**Comment by shukon** [comment]
> (...) comparing it to [the instructions](https://github.com/tulir/mautrix-signal/wiki/Bridge-setup-with-Docker#setup): (...)
> 
> Is something wrong? Maybe the instructions were misunderstood and the `data` config should be left with the original value?

I wondered about this. Switching to docker right now, it makes sense that the `data` config should be changed to comply with the volume path, right?

**Comment by joao-p-marques** [comment]
Yes, that's what I think. The configuration I passed earlier seems correct, but it still produces this error.
