### ISSUE TITLE
bridged DM-Room not working after "safety number has changed"

### ISSUE THREAD

**Issue by a22sc** [mautrix/signal#42]
I send s.o. messages over the bridge and wondered why he didn't response.
Opening the chat in Signal displays "Your safety number with _User_ has changed" and none of my messages were forwarded to signal.
A response like in other mautrix bridges would be good to be sure the sent message was forwarded.

The logs don't show anything as well.

**Comment by a000a** [comment]
signald doesn't handle these kind of events atm, btw

**Comment by macintoshme** [comment]
@a000a Did you ever work around this?

**Comment by a000a** [comment]
sorry for not replying.. as suggested by @thefinn93 maintainer of https://gitlab.com/signald/signald/
I followed https://gitlab.com/signald/signald/-/snippets/2051612

but anyway it would be nice of the mautrix-bridge to see if a message was received

**Comment by tulir** [comment]
There has been an error message for some time now
