### ISSUE TITLE
That command requires you to be logged in problem

### ISSUE THREAD

**Issue by tomnick** [mautrix/signal#422]
Signal bridge bot installed and runs so far. Successfully logged in!
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Successfully generated, registered and stored prekeys! 🎉

Trying to pm the first number and getting the following error:

That command requires you to be logged in

I am logged in as you can see above. 
mautrix-signal v0.4.99+dev.e33fa956

**Comment by tulir** [comment]
That looks like an old version of the bridge, try with the latest version

**Comment by makoeppel** [comment]
Same issue here with version:

[mautrix-signal](https://github.com/mautrix/signal) v0.4.99+dev.[959eb7ea](https://github.com/mautrix/signal/commit/959eb7eaf9eb648f97b8e85d7650ea87f2639cd1) (Jan  7 2024, 21:21:13)

**Comment by tulir** [comment]
That's an old version too

**Comment by makoeppel** [comment]
Okay that's strange I just encountered this when pulling the new version of https://github.com/spantaleev/matrix-docker-ansible-deploy they changed from the Python based bridge to this one. But than I will open an issue on their side and link this.

**Comment by makoeppel** [comment]
After the update to:

[mautrix-signal](https://github.com/mautrix/signal) v0.4.99+dev.[de8c8d97](https://github.com/mautrix/signal/commit/de8c8d97c23dc1982686a698162b45f1f112155b) (Jan 10 2024, 17:17:36)

It works for me again
