### ISSUE TITLE
"ffmpeg": executable file not found in $PATH

### ISSUE THREAD

**Issue by tomnick** [mautrix/signal#423]
Bridge running fine sending text messages and pics. Receiving or sending voice messages results in the following error:

Receiving:
`Failed to handle attachment : failed to convert audio to ogg/opus: ffmpeg error: exec: "ffmpeg": executable file not found in $PATH`

Sending:
`Your message may not have been bridged: failed to convert attachment: ffmpeg error: exec: "ffmpeg": executable file not found in $PATH`

What could be wrong?

**Comment by tulir** [comment]
As the error message suggests, ffmpeg wasn't found
