### ISSUE TITLE
unsupported msgtype m.location

### ISSUE THREAD

**Issue by tomnick** [mautrix/signal#424]
Trying to send my location but doesn't work.

`Your message was not bridged: unsupported msgtype m.location`

Am I missing anything?

mautrix-signal v0.4.99+dev.de8c8d97 (Jan 10 2024, 17:17:36)

**Comment by maltee1** [comment]
You're not missing anything, Location messages aren't yet supported: https://github.com/mautrix/signal/blob/main/ROADMAP.md

Signal itself doesn't support location messages (it supports looking up locations, but then sends the location as image+caption), so to bridge location messages, the bridge would have to turn the location into some kind of link. Ideally with an image.
