### ISSUE TITLE
Migration not working after upgrade

### ISSUE THREAD

**Issue by yousefamar** [mautrix/signal#426]
I think this is a similar issue to #405, but a different error:

```
Jan 19 15:11:53 ip-XXX-XX-XX-XX matrix-mautrix-signal[3562371]: Migrating legacy log config
Jan 19 15:11:53 ip-XXX-XX-XX-XX matrix-mautrix-signal[3562371]: Jan 19, 2024 15:11:53 ERR Failed to get lost portals error="pq: relation \"lost_portals\" does not exist"
```

For context, I was on a probably relatively old version (I didn't note which) deployed using https://github.com/spantaleev/matrix-docker-ansible-deploy/. I then tried upgrading, and got an error saying "upgrade mautrix-signal to v0.4.3 first", so I tried pinning to that version and instead got a range of different errors. So I decided to just start fresh by deleting everything mautrix-signal related (postgres DB, configs, systemd files) but I haven't deleted old rooms, I figured they would just be ignored, don't know if that's relevant.

I'm not sure if this is an actual bug or an issue with my setup, but I picked bug as it's upgrade rather than installation, so any tips or pointers much appreciated!

**Comment by tulir** [comment]
That error doesn't affect anything
