### ISSUE TITLE
S -> M mentions use matrix user's puppet's displayname

### ISSUE THREAD

**Issue by maltee1** [mautrix/signal#443]
`m.mentions` is correct, the matrix.to link also points to the actual matrix user, but the displayname used in `body` and `formatted_body` is that of the user's puppet. In my case it looks like this:
```
<a href="https://matrix.to/#/@malte:maltee.de">Malte E (Signal)</a>
```
Schildichat ignores the text and just loads the user's correct displayname and I suppose so does element. I guess maybe that's why it hasn't been noticed yet. Element X uses the one provided in the text.

**Comment by tulir** [comment]
It has been noticed, it was intentionally written that way because finding the real displayname is much more effort

**Comment by maltee1** [comment]
So... Are you planning on changing this or should I close the issue?
