### ISSUE TITLE
Question: what is status of libsignal-ffi?

### ISSUE THREAD

**Issue by Marcool04** [mautrix/signal#455]
Hi there,

Congratulations on getting the go rewrite out there! It is great that you have been able to decouple `mautrix-signal` from `signald` which was a considerable resource drain for me at least.

I simply have a kind of background question: I maintain the Arch Linux AUR package for [mautrix-signal](https://aur.archlinux.org/packages/mautrix-signal), and while I was transitioning it over to the go build I noticed that you start by pulling in `libsignal` and then use cargo to build the `libsignal_ffi.a` file (a big chunk at over 300Mb). I imagine that's where a lot of the API is located?

Because I wanted to keep package separation neat, I checked out `libsignal` separately. It's a bit of a mysterious repo really isn't it, with all kinds of different bindings plonked in there together! There was already a `libsignal-client` package available [in AUR](https://aur.archlinux.org/packages/libsignal-client) for instance, but it builds only the Java part, and does not provide `libsignal_ffi.a`

I built this and put it in the AUR so the component is now available there: [libsignal-ffi](https://aur.archlinux.org/packages/libsignal-ffi).

Do I understand things correctly that this is a rust library that is designed to be "consumed in languages that understand C, such as Swift, as it says here: https://github.com/signalapp/libsignal/tree/main/rust/bridge/ffi. Because then, if I do, regarding that Swift build, this page here: https://github.com/signalapp/libsignal/tree/main/swift says that

```
...
Development as a package is supported as a lightweight convenience
(as well as a cross-platform one), but the CocoaPods build is considered
the canonical one.
```

Does this mean that Signal Messenger LLC might decide to drop that `libsignal_ffi` part? Or would they still keep the C API available for other reasons? Or are there clear indications from them that they are going to keep that part going?

Just asking out of curiosity and to make sure I have understood the architecture of the rebuild. Thanks for any info and for your time working on this bridge (and all the others!)

Regards,
Mark.

**Comment by tulir** [comment]
libsignal handles all the signal crypto, libsignal-ffi is an FFI/C interface for libsignal, not much more to it than that. No way to predict what signal will or will not do (they don't develop software in the open, they just publish sources when making releases)

**Comment by Marcool04** [comment]
Ok. Thanks for that. Keep up the good work 👏
