### ISSUE TITLE
Bridge no longer working with Dendrite

### ISSUE THREAD

**Issue by pix** [mautrix/signal#457]
Hi.

I was using mautrix-signal as of today when I upgraded by mistake. It seems mautrix-signal / the go bridge library now complain that dendrite is outdated:

```
mautrix-signal  | 2024-02-18T17:33:55Z DBG Checking connection to homeserver
mautrix-signal  | 2024-02-18T17:33:55Z INF Starting HTTP listener address=0.0.0.0:29328
mautrix-signal  | 2024-02-18T17:33:55Z DBG Request completed duration=60.558624 method=GET req_id=1 response_length=189 response_mime=application/json status_code=200 url=https://homeserver/_matrix/client/versions?user_id=%40signalbot%3Ahomeserver
mautrix-signal  | 2024-02-18T17:33:55Z FTL The homeserver is outdated (supported spec versions are below minimum required by bridge) bridge_requires=v1.4 server_supports=v1.2
```

It seems related to https://github.com/mautrix/go/blob/b1b1c97a115cf3e8d72c81cdbb090a546df5dbb0/bridge/bridge.go#L319

But I can't find any reference nor traceback the origin of the requirement. Is this deliberate ?

Sincerly yours,
C.M.

**Comment by troed** [comment]
Dendrite API is lagging behind. tulir has added a flag to the bridge to disregard the version check. That, together with running the latest commits to Dendrite will get the bridge working again.

**Comment by niebloomj** [comment]
I am new to signal bridge and I am getting this error and can't onboard. How do I enable this flag mentioned?

**Comment by troed** [comment]
I wrote a blog post detailing my steps:

https://blog.troed.se/2024/02/19/mautrix-signal-bridge-dropping-dendrite/

**Comment by tulir** [comment]
The tldr is that you need a Dendrite version from February 2024 or later (there are no releases as of writing) and use the `--ignore-unsupported-server` flag for the bridge.
