### ISSUE TITLE
E2BE doesn't seem to work ? 

### ISSUE THREAD

**Issue by wrenix** [mautrix/signal#458]
Like in #43 

Documentation is lost of the issue (github wiki is closed and docs does noy show such part).

my registration.yaml looks:
```yaml
todo: in some minutes
```

logs show:
```
todo: in some minutes
/sync 500
```

synapse logs:
```
todo: in some minutes
/sync NotImplemented
```

**Comment by tulir** [comment]
The place to debug setup issues is still the Matrix room, which is linked in the repo readme, as well as the github issue templates

**Comment by wrenix** [comment]
Really?
