### ISSUE TITLE
Unable to send messages to groups: fetchNewGroupCreds error: creds.PNI != d.PNI

### ISSUE THREAD

**Issue by Virkkunen** [mautrix/signal#468]
I am unable to send messages to groups, with the following error: `⚠ Your message may not have been bridged: fetchNewGroupCreds error: creds.PNI != d.PNI`. There are no issues sending and receiving messages to direct chats, or receiving messages on group chats, only sending them on group chats.
Bridge is on the latest v0.5.0 and I'm hosting with [https://github.com/spantaleev/matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy)
Source of a message that wasn't bridged:
```json
{
  "type": "m.room.message",
  "sender": "@me:domain.tld",
  "content": {
    "msgtype": "m.text",
    "body": "message test",
    "format": "org.matrix.custom.html",
    "formatted_body": "message test"
  },
  "origin_server_ts": 1709371469278,
  "unsigned": {
    "age": 44,
    "transaction_id": "m1709371469214.3"
  },
  "event_id": "$zVIpoNx3gX9YTX5exYSQkZj8OYAQ2CdmhgOpZuJRyL0",
  "room_id": "!UBnBbGvPezilJFXjlX:domain.tld"
}
```

**Comment by Virkkunen** [comment]
I've been using Signal with Beeper for a while now due to this issue, but it started happening on Beeper as well, however just right now I tried sending a message to a group and Beeper told me I was logged out. It's weird since I could still send and receive messages on private chats, and receive messages just as fine on groups. I logged out and in again on Beeper and my self hosted instance and I'm able to send messages to groups again.

**Comment by tulir** [comment]
Interesting, had you changed anything in your Signal account recently before it started happening?

Your session was definitely somehow broken, PNI prekey uploads were returning 422s. I added a workaround to delete sessions on 422 which is what Signal Desktop does too, but I don't know why Signal works like that. I guess this was just another effect of the session being broken.

**Comment by Virkkunen** [comment]
> Interesting, had you changed anything in your Signal account recently before it started happening?
  
I'm thinking here, the only thing that I changed was that I added a username to my account, nothing else. Wasn't using Signal app for anything other than calls. Still weird how everything but sending group messages was working.
