### ISSUE TITLE
Move keepalive messages to DEBUG level

### ISSUE THREAD

**Issue by ainola** [mautrix/signal#473]
Hello! Thanks for maintaining this great suite of software

I have my bridge loglevel set to INFO - there's a ton of lines being outputted about keepalives. I was hoping that https://github.com/mautrix/signal/blob/ecc78fabe758f771b722afd4049265591c46c8c2/pkg/signalmeow/web/signalwebsocket.go#L300 could be moved to DEBUG since it's quite noisy.

Thanks!

**Comment by tulir** [comment]
Note that debug logs are needed for debugging any issues that come up, so the logs will still be noisy even if it's moved to debug level

**Comment by ainola** [comment]
Sure, I wasn't hoping to eradicate all messages. But I feel that this doesn't really fit into INFO levels as it's such a repetitive action that doesn't really have any purpose except for debugging an issue. At INFO levels it drowns out other informational output. I imagine that if connectivity issues are being debugged then the level can be adjusted by the reporter 🙂
