### ISSUE TITLE
Unable to send messages: Verification failure in zkgroup

### ISSUE THREAD

**Issue by storm1er** [mautrix/signal#483]
Everything was working well, nothing special happened then

```
Your message may not have been bridged: 110: Verification failure in zkgroup
```

Messages started to appear in some conversations (not all)

I still receive messages that are sent to me or messages I send from the signal app but I can't send messages from the bridge

**Comment by antonywinn** [comment]
I'm also seeing this issue, started in that last day.

**Comment by maltee1** [comment]
> I'm also seeing this issue, started in that last day.

It's already fixed. You need to update.

**Comment by niklaskorz** [comment]
@tulir could you release a 0.5.1 with this fix so we can update it in nixpkgs?

**Comment by maltee1** [comment]
There will probably be a release tomorrow - the go bridges get a release on 16th of each month - if they get a release

**Comment by storm1er** [comment]
Well, the update is done but the error is still here.

I guess the issue will not appear on currently working or new conversations but how do we do for existing errored conversations?

**Comment by tulir** [comment]
All groups will automatically start working after upgrading, there's no such thing as "existing errored conversations"

**Comment by niklaskorz** [comment]
> All groups will automatically start working after upgrading, there's no such thing as "existing errored conversations"

Yup the fix works fine here for all groups, existing and new ones

**Comment by storm1er** [comment]
Ok, Config issue caused the init container to have a different image tag than the main container. My fault, it's fixed =)

**Comment by phesch** [comment]
On version v0.6.0, I cannot send messages to groups, though I can receive messages from others in the group. Has anyone else experienced this?
