### ISSUE TITLE
Upgrading from mautrix-signal 0.4.3 to 0.6.0 ended up with users not able puppet due to unique constraint puppet_number_key

### ISSUE THREAD

**Issue by samip5** [mautrix/signal#505]
It seems that something wierd went wrong? I did an in-place upgrade for mautrix-signal 0.4.3 to 0.6.0 and it migrated the database fine. However when a user tries to login again and use it, there are duplicate key value errors with puppet_number_key when handling contact list.

```
Apr 23 10:01:35 matrix-kapsi-fi mautrix-signal-amd64[1075311]: 2024-04-23T10:01:35+03:00 ERR Failed to save puppet to database after updating error="pq: duplicate key value violates unique constraint \"puppet_number_key\"" action="handle contact list" function=Puppet.UpdateInfo signal_user_id=d2343d45-3be5-4fb6-8458-fbbdaa1d1e0a user_id=@<snip>:kapsi.fi
```

**Comment by maltee1** [comment]
have you tried upgrading to 0.5.0 first and then to 0.6.0?

**Comment by samip5** [comment]
> have you tried upgrading to 0.5.0 first and then to 0.6.0?

No, went straight to 0.6.0.

**Comment by maltee1** [comment]
Maybe give it a try?

**Comment by samip5** [comment]
I just truncated the puppet table, and "fixed" it already.
