### ISSUE TITLE
Messages sent via Beeper or Element disappear from Signal Android upon delivery

### ISSUE THREAD

**Issue by ZaeGitHub** [mautrix/signal#509]
I am not sure if this is an issue with Beeper or the bridge (I don't see how it would be Beeper, but you never know), but when I send messages using this bridge (self-hosted) through Beeper, they show up on Signal Desktop, Android, etc... until they are delivered. Then they, for some reason, disappear entirely from Signal Android. ONLY Signal Android.

How can I troubleshoot this? Are there debug logs I can turn on in the bridge that may explain this?

**Steps to Reproduce**

- Self-host this bridge, using Bridge Manager (bbctl) to install it. 
- Authenticate yourself by sending a message to the bridge.
- Open Signal Android on your phone
- Send a message to someone else via Beeper mobile or desktop
- Before delivery, if possible, notice the message being sent. 
- After delivery, notice the message is missing from Signal Android.

Either way, the other user **does actually get your message.**

**Comment by brknkfr** [comment]
I'm experiencing the same on a self-hosted bridge without Beeper. This happens for example, when I send a message over Element (Web, Android, X), so this has to be a bug in the bridge. @ZaeGitHub, you want to change your bug title maybe?

**Comment by ZaeGitHub** [comment]
Thanks for reporting this on a separate platform @brknkfr. Changed the title to reflect this occurring in Element too, which IMO does lend credence to this being a bridge issue.

**Comment by brknkfr** [comment]
Still happening with version v0.6.2. As I still use the backup function of the Signal app, this is somehow unfortunate ... Will this be fixed with an upcoming release?

**Comment by ZaeGitHub** [comment]
+1, I can confirm this is also happening to me. The problem appears to be this bridge in particular, as the Beeper locally-hosted Android bridge works fine.

**Comment by neonblind** [comment]
For me it's exactly the other way around. self-hosted bridge, E2BE enabled, double puppeting manually enabled. message i write with the native signal client wont appear in my own matrix client.

**Comment by ZaeGitHub** [comment]
Is this fixed in the next version? Should it already be fixed? I ask because it is definitely still occurring in the most recent version of the bridge. I am happy to provide logs from the container I am running the bridge in, if that helps.
