### ISSUE TITLE
failed to save kyber prekey

### ISSUE THREAD

**Issue by sub2010** [mautrix/signal#515]
Login in my Signal Account doesnt work.

Error Code
Error with prekeys: error generating and registering PNI prekeys: failed to generate and save next kyber prekey batch: failed to save kyber prekey: context deadline exceeded

**Comment by Bleala** [comment]
I've got the same issue, but in my case the error message says `ACI` instead of `PNI`

```
Error with prekeys: error generating and registering ACI prekeys: failed to generate and save next prekey batch: failed to save prekey: context deadline exceeded
```

Is there a fix for this problem?

**Comment by sub2010** [comment]
The error still exists, is there a workaround?

**Comment by sub2010** [comment]
Thank you for fixing the problem!
