### ISSUE TITLE
Replying to messages contains the matrix link in the signal message

### ISSUE THREAD

**Issue by kolaente** [mautrix/signal#519]
When replying to a signal message from matrix, the message sent in signal contains a link to matrix.

In Matrix:

![image](https://github.com/mautrix/signal/assets/13721712/1414af04-2ea7-466c-9a10-53a98834d9b8)

In Signal:

![Screenshot_20240617-163456](https://github.com/mautrix/signal/assets/13721712/d2fecd23-932d-4982-ba75-7ac1cd754e6f)

I'm using v0.6.2.

**Comment by alarig** [comment]
I have the same issue since the upgrade to the release of yesterday, here is the source of one of my reply:
```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "> <@signal_3ff36629-a96e-4948-b88b-fd773a033f33:matrix.swordarmor.fr> tu deny?\n\na priori ouais",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!DFrJRVYrBvHrNKYxGU:matrix.swordarmor.fr/$4WKZocbpLHW1kGwsExIC0d1-1qRseV0-QsKCAhFxEss?via=matrix.swordarmor.fr\">In reply to</a> <a href=\"https://matrix.to/#/@signal_3ff36629-a96e-4948-b88b-fd773a033f33:matrix.swordarmor.fr\">@signal_3ff36629-a96e-4948-b88b-fd773a033f33:matrix.swordarmor.fr</a><br>tu deny?</blockquote></mx-reply>a priori ouais",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$4WKZocbpLHW1kGwsExIC0d1-1qRseV0-QsKCAhFxEss"
      }
    }
  }
}
```

**Comment by tulir** [comment]
There was a bug with replies in encrypted rooms when sent from clients that don't use matrix-rust-sdk or mautrix-go. Element web/desktop with rust crypto as well as Element X should work fine. Unencrypted rooms should work fine with all clients. The release notes have been updated to note that the release should be skipped if other clients are used in encrypted rooms

**Comment by alarig** [comment]
I confirm that it works if I rebuild the bridge with https://github.com/mautrix/go/commit/afeadfb15feeab88aca99776ef3c0c9828ea6515
Thanks a lot for the fix!

**Comment by kolaente** [comment]
Since downgrading the bridge is not an option, is there a way to fix this without manually building the bridge?

I'm using Element web in the latest version, so that should work fine? (it doesn't)

**Comment by tulir** [comment]
Old element web logins may still use js crypto, they haven't finished rolling out rust crypto (but are planning to within a few weeks). Relogining to element web should switch to rust crypto

All commits of the bridge are also built in CI

**Comment by kolaente** [comment]
Seems to work after logging out and back in again. Thanks!

**Comment by djmaze** [comment]
> Since downgrading the bridge is not an option, is there a way to fix this without manually building the bridge?

Same problem here but there are non-Rust SDK based clients in the mix, so logging out and back is probably not a solution.

So downgrading the bridge would not work? Are breaking database migrations involved?

**Comment by dreirund** [comment]
Also:

* The reply text is not separated by a newline from the quote.
* On signal side, the reply is not logically a reply but a standalone message.
* When on Matrix a reply is given in thread, then on Signal side there is a standalone new message without any reference.
* When on Matrix the thread is deleted by deleting the parent message of the thread, on Signal the child messages of the thread are not deleted.
