### ISSUE TITLE
Message editing results in duplicated message on signal side; deletion of the old message on signal side results in removal of edited message on Matrix side.

### ISSUE THREAD

**Issue by dreirund** [mautrix/signal#522]
I use mautrix-signal version 0.6.2 as [installed on yatrix.org](https://yatrix.org/wissen/anleitungen/bruecken/) in double pupetting mode.

When I send a message to a chat, and then edit the message, on the signal side the message is not edited but duplicated (the original message still there, and the edited sent as a new message. With an Asterisk prepended):

*Original message, in Matrix:*  
<hr>

![01_-_msg-matrix](https://github.com/mautrix/signal/assets/1590519/98c81fff-0b5a-425b-93cc-893154abf82c)  
<hr>

*Original message, in Signal:*  
<hr>

![02_-_msg-signal](https://github.com/mautrix/signal/assets/1590519/0a73a06c-4eae-45fc-8e3e-4bdc7f9455dc)  
<hr>

*Edited message, in Matrix:*  
<hr>

![03_-_msg-matrix-edited](https://github.com/mautrix/signal/assets/1590519/df708e98-3cf8-4f41-b98f-64fa5b6a89cd)  
<hr>

*Edited message, in Signal:*  
<hr>

![04_-_msg-signal-edited](https://github.com/mautrix/signal/assets/1590519/0e7c1b69-13bd-4d5b-8d60-d8663dce12f7)  
<hr>

* When I then delete from within the native signal client the old message, the edited message in the Matrix client (I use "[SchildiChat](http://schildi.chat/)", which is [Element](http://element.io) based) is deleted, leaving me:
  - With no message on the Matrix side,
  - with the edited message on the signal side:

  *Deleted original, in Signal:*  
  <hr>
  
  ![05_-_msg-deleted-signal](https://github.com/mautrix/signal/assets/1590519/fddddcc0-af36-4f4a-9f8e-ac5a7c7fb7f6)  
  <hr>
  
  *Deleted original messgage, in Matrix (no message left at all):*  
  <hr>
  
  ![06_-_msg-deleted-matrix](https://github.com/mautrix/signal/assets/1590519/ecb10fbd-5a55-4ff6-8880-36f1a5d86651)
  <hr>
  
  *(Note that in the Matrix client the username in the message "Message deleted by [...]" is my Signal username, not my Matrix username.)*

* When I instead delete from the native signal client the edited message, on the matrix side the edited message is removed and the original message is restored *(no screenshots taken.)*

Regards!

**Comment by tulir** [comment]
the bug mentioned in the release notes probably affects edits as well
