### ISSUE TITLE
Missing Prometheus metrics in v0.7.0

### ISSUE THREAD

**Issue by wrenix** [mautrix/signal#532]

**Comment by tulir** [comment]
Not currently planned

**Comment by Ma27** [comment]
@tulir is there any way to monitor the bridge's connectivity? I.e. I used to have an alert if my bridge failed to connect.

**Comment by sumnerevans** [comment]
@Ma27 the `homeserver` -> `status_endpoint` can be used to get updates about the connectivity of users on the bridge:

https://github.com/mautrix/go/blob/da2780bcbe0a1d9e0ebf0010ad7bd6fa6bc42f00/bridgev2/matrix/mxmain/example-config.yaml#L127-L130

**Comment by Ma27** [comment]
@tulir @sumnerevans given that mautrix-whatsapp will also switch to the new bridge version, would you be willing to accept a PR that re-adds this?

**Comment by litetex** [comment]
Ran into the exact same problem while trying to update...
Was wondering why the metrics are missing as I couldn't find any mention inside the changelog until I found this issue.

@sumnerevans 
> the `homeserver` -> `status_endpoint` can be used to get updates about the connectivity of users on the bridge:

I couldn't find any documentation online how or with what this can be collected (and then be made available for prometheus or similar tools).
Could you give a hint where this can be found?
