### ISSUE TITLE
Read marker sync with reactions

### ISSUE THREAD

**Issue by freaktechnik** [mautrix/signal#534]
Based on observation it seems like the bridge syncs the read marker to the last event in a room (presumably set to read). At least with element for android this seems to include reactions, but signal seems to only support read states for actual messages. So setting the read state to the last seen reaction can lead to messages after the message that was reacted to to be marked unread.

That is at least what fits the pattern I've been seeing.

Version: [mautrix-signal](https://github.com/mautrix/signal) v0.7.0+dev.[31a4522e](https://github.com/mautrix/signal/commit/31a4522ee66e5b1d52055ea5fd093602bb7d243e) (Sun, 18 Aug 2024 13:43:52 +0000)

**Comment by tulir** [comment]
There's no such behavior with reactions. Marking the room as read on Matrix will mark all messages as read on Signal.

**Comment by freaktechnik** [comment]
> Marking the room as read on Matrix will mark all messages as read on Signal.

Is that a workaround recommendation to signal re-pushing notifications? Because I've had signal show me the notification for a message again after having read the message (and room) in matrix multiple times recently. The only thing that seemed consistent was that the last event element was showing was a reaction.
