### ISSUE TITLE
Double Puppeting: Configuration unclear and inconsistent with the documentation

### ISSUE THREAD

**Issue by tom-ch1** [mautrix/signal#541]
environment:
* debian bookworm
* matrix-synapse 1.113.0+bookworm1
* mautrix-signal-amd64_v0.7.0 (updated from v0.6.0 and from earlier legacy versions)

https://docs.mau.fi/bridges/general/double-puppeting.html explains how to setup double puppeting with bridges in general.

The shared secret method states in step 1:

> Add the login shared secret to bridge → login_shared_secret_map in the config file under the correct server name.

However, `mautrix-signal -e` creates a config file with substantial differences:

1. there is a `double_puppet:` section (whereas in the docs, double puppeting is setup in the `bridge` section) 
2. the token is specified as: `secrets: <server-name>: as_token:<token>` (whereas in the docs, that should be `login_shared_secret_map: <server-name> : <token>`)

It is therefore unclear how to setup double-puppeting with mautrix-signal

**Comment by tulir** [comment]
The docs will be updated later

**Comment by tom-ch1** [comment]
and which configuration is supposed to work?

**Comment by tulir** [comment]
The docs work after adjusting the field names (`bridge`->`login_shared_secret_map` = `double_puppet`->`secrets`). Deprecated methods are not supported.

**Comment by tom-ch1** [comment]
> The docs work after adjusting the field names (`bridge`->`login_shared_secret_map` = `double_puppet`->`secrets`). Deprecated methods are not supported.

I don't understand what you mean :-) should it work if the names are adjusted?

**Comment by tom-ch1** [comment]
Ok, I decyphered the issue:
1. shared secret method as described in https://docs.mau.fi/bridges/general/double-puppeting.html does not work anymore with mautrix-signal v0.7.0
2. in mautrix-signal v0.7.0, you should use the appservice method
3. HOWEVER: on the bridge side (in config.yaml of mautrix-signal, you must not follow the documentation, **it is wrong**!
4. Instead, you replace what should go under ```bridge:``` with the following section:
```
double_puppet:
    servers:
        anotherserver.example.org: https://matrix.anotherserver.example.org
    allow_discovery: false
    secrets:
        my.server.org: "as_token:myVerySecretString" 
```
and put in `myVerySecretString` what you setup in `doublepuppet.yaml` under `as_token: myVerySecretString`
No quotes are needed there

**Comment by tom-ch1** [comment]
Thanks @tulir for the documentation update https://github.com/mautrix/docs/commit/8f99433de8cf33c08332562661dba1a17c4b1aa0 this clears everything up

**Comment by andreasofthings** [comment]
When running [mautrix-signal](https://github.com/mautrix/signal) v0.7.2+dev.[ad41c86f](https://github.com/mautrix/signal/commit/ad41c86f116f484a57b7df07bc082f33fc12d908) (Sat, 19 Oct 2024 20:30:22 UTC), the following happens after I followed this documentation.

```
double-puppet: 
  secrets:
    <hostname>: "as_token:<as_token>
```

gives me 

```
ping-matrix
Signal bridge bot
You don't have double puppeting enabled.
```

This seemingly works with the whatsapp (however shared secret) and/or discord bridge, just not signal. Is there another substantial difference that I oversee?

**Comment by madduck** [comment]
I have the same issue with Signal, but also with Whatsapp and Slack, i.e. all the Megabridges.

This is the error I see in the bridge log:

```
{"level":"error","user_mxid":"@madduck:madduck.net","action":"setup double puppet","error":"failed to GET /_matrix/client/v3/account/whoami: M_UNKNOWN_TOKEN (HTTP 401): Invalid access token passed.","time":"2024-11-01T13:54:58.757836728+01:00","message":"Failed to create new user intent"}
```

and in Synapse's logs:

```
2024-11-01T16:16:07.540578+01:00 cymbaline synapse[61100]: 2024-11-01 16:16:07,539 - synapse.api.auth.internal - 287 - WARNING - GET-18001 - Invalid access token in auth: <class 'pymacaroons.exceptions.MacaroonDeserializationException'> cannot determine data format of binary-encoded macaroon.
```

I get the same error when trying the `login-matrix` manual method, although that mysteriously worked this morning for Slack, but not for the others.

I've poked at the database, but I cannot find where it might store a corrupted maccaroon or the like.
