### ISSUE TITLE
Config migration from < 0.7.0 to >= 0.7.0 does not generate a pickle key

### ISSUE THREAD

**Issue by BVollmerhaus** [mautrix/signal#544]
mautrix-signal 0.7.0 (or rather _bridgev2_) added support for encrypting keys in the database using a static encryption key configured via `encryption.pickle_key`. I would've assumed that this key would be generated automatically upon upgrading from 0.6.3 to 0.7.0 and used from there on (given [the default appears to be](https://github.com/mautrix/go/blob/v0.20.0/bridgev2/matrix/mxmain/example-config.yaml#L319) `'generate'`), but this is not the case; instead, [the key is simply set to](https://github.com/mautrix/signal/blob/v0.7.0/cmd/mautrix-signal/legacymigrate.go#L41) `'mautrix.bridge.e2ee'`.

Is there a concrete reason for this? As it stands, this seems like an oversight to me, and it'd seem much more prudent to generate a proper secure key upon upgrading the config.

**Comment by tulir** [comment]
The key can't be changed easily, so old instances need to use the key they were set up with. The key isn't that important, most people will store the config and database in the same place anyway.

**Comment by BVollmerhaus** [comment]
Hm, I'm aware that changing the key later on will be difficult/unsupported, but what exactly do you mean by "old instances"? Was database encryption already in place for <0.7.0 and statically used `'mautrix.bridge.e2ee'` as the key, thus preventing a change?

If not, and the key is generated once upon upgrading, why does it matter whether it's `'mautrix.bridge.e2ee'` or a random, more secure string?

In any case, I'd argue that the default behavior should be the more secure one (assuming that the new encryption feature had that goal in the first place), both for people with simple deployments and those with a properly separated database (where it would, of course, have the biggest impact).

**Comment by tulir** [comment]
No new encryption features were added, I just moved libolm's pickle key to the config instead of being hardcoded. The rest of the database is not encrypted in any case

**Comment by BVollmerhaus** [comment]
I see; that explains why it needs to remain as `'mautrix.bridge.e2ee'` for existing databases. Thanks for clarifying.
