### ISSUE TITLE
Login failed: non-200 status code (409) from devices response: Conflict

### ISSUE THREAD

**Issue by Virkkunen** [mautrix/signal#549]
I cannot login to the Signal bridge after a device change. I moved to a new phone, installed and logged in on Signal (as a new device) normally. My Signal bridge bot says there are no logins made, but when I try to login with the QR code, I get a `Login failed: non-200 status code (409) from devices response: Conflict`. On systemd logs I only have:
```
Sep 15 17:56:37 matrix systemd[1]: Started matrix-mautrix-signal.service - Matrix Mautrix Signal bridge.
Sep 15 17:57:07 matrix matrix-mautrix-signal[3825256]: 2024-09-15T15:57:07.436Z ERR confirmDevice error error="non-200 status code (409) from devices response: Conflict" action="perform provisioning" user_id=@vrkknn:vrkknn.net
```

I've tried this with two different devices (Galaxy S22 Ultra, Pixel 9 Pro), with and without Signal beta, and the issue persists

**Comment by tulir** [comment]
Signal blocks new devices from connecting if all other devices have a capability flag that the new device doesn't. In other words, your bridge is too old

**Comment by bbieberle** [comment]
i have the same issue running bridge version 0.7.0. I also moved to a new phone yesterday and was not able to log into the bridge again. i deleted my signal account and tried to register the newly created account but the issue persists.
Running Signal version 7.16.4. No other devices are connected to the signal account.

**Comment by Virkkunen** [comment]
For clarification, it actually was the bridge being too old. I'm using the matrix-docker-ansible-deploy playbook and had a variable `matrix_mautrix_signal_version: latest` to control which version to use. The issue was a typo (`signal` as `sgnal`), it didn't show any errors with it so I thought that was the latest version of the bridge.

**Comment by bbieberle** [comment]
i now switched to the docker tag "latest" from "v0.7.0". Now it seems to work. I am just confused, that it seems 0.7.0 is not latest

**Comment by Virkkunen** [comment]
> i now switched to the docker tag "latest" from "v0.7.0". Now it seems to work. I am just confused, that it seems 0.7.0 is not latest

0.7.0 is the latest release tag, but by using `latest` on that variable, it'll pull the latest commit from the repo and apply it. If you run `version` on your bridge bot, it'll reply with something like `mautrix-signal v0.7.0+dev.11686cbe (Sat, 14 Sep 2024 16:48:21 UTC)`. This +dev.xxxx points to the commit it pulled from.

**Comment by WowSuchRicky** [comment]
I have the same issue, but on 0.7.0: `[mautrix-signal](https://github.com/mautrix/signal) [v0.7.0](https://github.com/mautrix/signal/releases/v0.7.0) (Fri, 16 Aug 2024 12:19:42 UTC)` 

Any ideas what else could be causing that?

**Comment by tulir** [comment]
As already stated earlier, the error happens if the bridge is too old. The solution is to update the bridge.
