### ISSUE TITLE
Do you want a helm chart? 

### ISSUE THREAD

**Issue by wrenix** [mautrix/signal#560]
I made a helm chart here to deploy ghcr.io/matrix-org/matrix-authentication-service on Kubernetes:
https://codeberg.org/wrenix/helm-charts/src/branch/main/mautrix-signal

I can donate it here if you'd like it. If not, let this issue serve as a jumping off point for anyone who wants a helm chart or wants to fork a helm chart.

Quick question either way:
I'm actually not sure what license I should put on it 🤔 It uses the docker image from this repo, but this repo uses Apache2.0, however synapse itself uses AGPL. Does it matter if I use Apache2.0 or AGPL?

PS: Maybe i will write another Helm-Chart for slack in near feature ....

**Comment by tulir** [comment]
Other setup methods can be listed on https://docs.mau.fi/bridges/go/setup.html, but probably not in the bridge repo itself

Synapse's license doesn't affect the bridge, but the bridge is also AGPL (always has been)
