### ISSUE TITLE
mautrix-signal seems to be buffering or failing to send messages for awhile

### ISSUE THREAD

**Issue by fingon** [mautrix/signal#561]
Versions:
- mautrix-signal bridge docker image version (latest tag, week old)
- conduwuit homeserver latest docker image as (2 weeks old)

Sequence of events (T being the 'now' I looked at timestamps in the Signal client):

```
T-2h: I send 1 message
T-1h-ish: He sends me some things as well, then and later (about 3)..
T-45min: I send 2 more messages (in response to his 3 messages)
T-15min: He gets my 3 messages, and comments about the matrix buffer
```

I did see his messages (and even responded to them), but in the other direction the delivery of especially first message was delayed hours.

Is this a known bug or something I should try to get more data on? It has been happening at least 4 months, every now and then (we notice it perhaps once every two, three weeks, but I use the bridge a lot). I have upgraded the related containers to latest tag every two or three weeks.

fwiw I'm running the bridge on warning log level right now as it is bit spammy otherwise, but I can lower the log level if it helps to debug this.

**Comment by tulir** [comment]
The bridge doesn't have any buffering

**Comment by fingon** [comment]
Hm, any idea where the messages would have been buffered then? I have seen this with more than one client (Element iOS, Element Desktop; I switched recently to X iOS so not that yet).

**Comment by EchedelleLR** [comment]
@fingon I guess we need to wait for next release?

**Comment by fingon** [comment]
Theory is that this was conduit bug with exponential back off that conduwuit inherited.
