### ISSUE TITLE
Support new Voice Messages from Matrix <-> Element Clients

### ISSUE THREAD

**Issue by DoM1niC** [mautrix/signal#74]
Handle new Voice Messages from Element to your Appservice

**Voice Messages** are in OPUS as `audio/ogg` Container

equal to https://github.com/tulir/mautrix-whatsapp/issues/286

**Comment by frederictobiasc** [comment]
Hi,
do you have any link to this? The element issue I know of (https://github.com/vector-im/element-web/issues/1358) is still open.

**Comment by DoM1niC** [comment]
> Hi,
> do you have any link to this? The element issue I know of ([vector-im/element-web#1358](https://github.com/vector-im/element-web/issues/1358)) is still open.

what do you mean exactly the Voice Messages already implemented in Server <-> Clients (Web e.g.), yesterday @tulir added yesterday support for MSC in WhatsApp bridge and works Wonderful! 👍🏻  

iOS and Android Version of Element need to be added this Voice Message feature soon.... iOS is currently in progress and Android puhhh only FluffyChat got VoiceMessage Support currently

 Element -> Android seems to take time for native support.
