### ISSUE TITLE
Unable do decrypt message

### ISSUE THREAD

**Issue by Jab2870** [mautrix/signal#89]
![Untitled](https://user-images.githubusercontent.com/1909202/119054624-db0ebb80-b9bf-11eb-9367-c8f56d902559.png)
For some reason, the messages I receive are not decrypting. However, they
decrypt fine when using the official desktop signal client. Where can I look to
start debugging this

**Comment by Jab2870** [comment]
To add further to this, it is happening when several different people send
messages on both group and individual messages. However, it is not everyone.

**Comment by freaktechnik** [comment]
I've seen this happen every now and then but after making sure I logged in with every client I can usually decrypt these messages. It seems like it's using a key for a random device/session to encrypt and unless that client decrypts and gossips you can't read the message.
