### ISSUE TITLE
Essential documentation disappeared

### ISSUE THREAD

**Issue by samuelsadok** [mautrix/signal#93]
When I set up my mautrix-signal instance a few months ago, I used the instructions found on the GitHub wiki.

This seems to have been deleted around February (f066a698bbcf3bc6d07679d4953e4c4ca13cb456), however I can't find any Signal specific instructions on the new documentation page (how to join groups, how to set account names, etc). Where did those instructions go?

**Comment by tulir** [comment]
There was nothing else signal-specific than the authentication instructions. Those instructions are a bit simpler

**Comment by samuelsadok** [comment]
In my chat backlog with "Signal bridge bot" I have some more commands, for instance `raw --user list_groups {}`, `raw v1.accept_invitation {"groupID": "..."}` and `!signal set-displayname [name] [handle]` but maybe the bridge has evolved by now, rendering these commands obsolete (at least the display name seems to be set automatically now).

In any case I find the `raw` command useful for debugging purposes, so it might be worth mentioning it with a link to the [signald command reference](https://github.com/thefinn93/signald#socket-protocol).

**Comment by tulir** [comment]
Listing groups and accepting invitations manually is indeed no longer necessary, accepting the Matrix invite will automatically accept the Signal invite too. Setting the profile name is required and is mentioned in the auth docs.
