### ISSUE TITLE
display names not shown (full name first name, last name)

### ISSUE THREAD

**Issue by steadfasterX** [mautrix/signal#98]
the displaynames `full_name`, `first_name` and `last_name` are not working. I remembered that the TG bridge uses a space between and that worked.

not working:

```
# Bridge config
bridge:
[...]
    displayname_preference:
    - full_name
    - first_name
    - last_name
```

working:

```
# Bridge config
bridge:
[...]
    displayname_preference:
    - full name
    - first name
    - last name
```

so a space between and not an underscore. then it works as expected (at least here).

If someone else would confirm I could open a PR on that.

**Comment by nexusVI** [comment]
Can confirm that it seems to work correctly with spaces.

**Comment by ShadowJonathan** [comment]
This seemed to also have fixed my problem.

**Comment by tulir** [comment]
Underscores are the canonical form, but it also allows spaces: https://github.com/mautrix/signal/blob/v0.2.2/mautrix_signal/puppet.py#L272-L281

Restarting usually helps with name problems though
